#!/bin/bash
# pepper, (c) grupo SIESTA, 24-07-2007
#
# Script que lanza la generación de la caché de la sincroguia en background

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Ejecutar generacion cache XML
run-http.sh /bin/gc-sincro.sh &

# Resultado OK
enviar_xml_ok
