#!/bin/bash
# pepper, (c) grupo SIESTA, 16-08-2007
#
# Script que lanza la descarga de imagenes en background

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Lanzar proceso de descarga
run-http.sh /bin/getsincroimg.sh &

# Resultado OK
enviar_xml_ok
