#!/bin/bash
# jotabe, (c) Grupo SIESTA, 08-11-2007
#
# Borrar fragmentos de grabacion huerfanos (ficheros .fmpg, .mpg, .idx, .midx)
# Tambien se borra el timeshift actual, al cambiar de canal se activa de nuevo.
# borrarHuerfanos?dir

# Obtener parametros
CridFolder=`echo $QUERY_STRING | cut -d"&" -f1`

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"
LOG=/var/log/fmpg-huerfanos.log
SCRIPT=/tmp/fmpg-huerfanos.sh
FMPG_HUERFANOS=/tmp/fmpg-huerfanos.txt

# Log del proceso
echo "<b>`date` Borrado .fmpg huerfanos: carpeta=$CridFolder</b>" >> $LOG
echo -n "" > $SCRIPT

# Comprobar carpeta
if [ -d $CridFolder ]; then
	# Obtener fmpg huerfanos
	fmpgHuerfanos.sh ${CridFolder} 2>/dev/null > $FMPG_HUERFANOS

	# Recorrer lista ficheros
	files=""
	for fileFMPG in `cat $FMPG_HUERFANOS`; do
		# Borrar fichero .fmpg
		echo "rm -f ${fileFMPG}*" >> $SCRIPT
		# Lista de ficheros para calcular espacio usado
		files="${files} ${fileFMPG}*"
	done

	# Comprobar ficheros a borrar
	if [ ${#files} -ne 0 ]; then
		# Calcular espacio usado
		du=(`du -ch ${files} | tail -1`)

		# Borrar ficheros
		cat <<- --EOF-- >> $LOG
		Script a ejecutar:
		---- Inicio ----
		`cat $SCRIPT`
		---- Fin ----
		--EOF--
		eval "(`cat $SCRIPT`) >> $LOG 2>> $LOG"
	else
		du="0 bytes"
	fi

	# Log
	echo "`date` Fin borrado .fmpg huerfanos (`cat $FMPG_HUERFANOS | wc -l` ficheros, $du)" >> $LOG

	# Resultado OK
	enviar_xml_ok
else
	# Resultado ERROR
	enviar_xml_err
fi

# Eliminar ficheros temporales
rm -f $SCRIPT
rm -f $FMPG_HUERFANOS
