#!/bin/bash
# pepper, (c) Grupo SIESTA, 27-07-2007
#
# Script que cancela una grabacion y retorna el resultado en XML

# Obtener parametros
pid=`echo $QUERY_STRING | cut -d"-" -f1`

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi

# Log del proceso
echo "`date` Petición de cancelación de grabación: $QUERY_STRING" >> /tmp/record.log

# Enviar peticion a wavebox
wcpre=`cat /data/RA_FILE | wc -l`
echo "CANCEL $pid" > /dev/tcp/localhost/2010
sleep 4
wcpost=`cat /data/RA_FILE | wc -l`

# Comprobar resultado
if [ $wcpre -gt $wcpost ]; then
	# Resultado OK
	enviar_xml_ok
	echo "`date` Resultado: OK" >> /tmp/record.log
	# Borrar fichero cache de grabacion
	rm -f ${Cache}/*${pid}.refXML 2> /dev/null
else
	# Resultado NO OK
	enviar_xml_err
	echo "`date` Resultado: NOK" >> /tmp/record.log
fi
