#!/bin/bash
# jotabe, pepper, (c) Grupo SIESTA, 02-11-2007
#
# Copiar grabacion (ficheros crid, fmpg, mpg, idx, midx)
#

# Por defecto, copiamos la grabación, no la movemos
mover=0

# Obtener parametros
if [ $# -ge 2 ]; then
	Cridfile=$1
	DIR_DESTINO=$2
	if [ $# -eq 3 ]; then
	    mover=$3
	fi
else
	Cridfile=`echo ${QUERY_STRING} | cut -d"&" -f1`
	DIR_DESTINO=`echo ${QUERY_STRING} | cut -d"&" -f2`
	mover=`echo ${QUERY_STRING} | cut -d"&" -f3`
fi

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
LOG=/tmp/copiar_crid.log
LOGPROC=/tmp/copiar-crid-proc.log
SCRIPT=/tmp/copiar_crid.sh
Cachefile=${Cache}/`basename $Cridfile .crid`.refXML
DIR_ORIGEN=`dirname $Cridfile`

# Log del proceso
echo "`date` Copiar crid: $Cridfile" >> $LOG
echo -n "" > $SCRIPT
echo -n "" > $LOGPROC

# Comprobar carpetas y fichero
if [ -d $DIR_ORIGEN -a -d $DIR_DESTINO -a -f $Cridfile ]; then
	# Procesar fichero crid
	eval `www-tools crid2var ${Cridfile}`
	echo "Fichero: `basename ${Cridfile}` -> $Titulo ($num_fmpg, $fmpg0)" >> $LOG
	echo "`date` Fichero: `basename ${Cridfile}` -> $Titulo ($num_fmpg, $fmpg0)" >> $LOGPROC
	
	# Copiar crid: Lo duplico con otro nombre para que el fichero de caché no sea el mismo que el original
	CridfileCopy=`dirname ${Cridfile}`/`hostname`_`basename ${Cridfile}`
	echo "cp ${Cridfile} ${CridfileCopy} 2>> $LOGPROC" >> $SCRIPT
	echo "mv ${CridfileCopy} $DIR_DESTINO 2>> $LOGPROC" >> $SCRIPT
	echo "echo Copiando ${CridfileCopy} a $DIR_DESTINO >> $LOGPROC" >> $SCRIPT
	
	# Borrar fichero .refXML
    echo "rm -f $Cachefile" >> $SCRIPT

	# Nombres fragmentos
	i=0
	while [ $i -lt $num_fmpg ]; do
		# Nombre fragmento
		TMP='$fmpg'${i}
		eval "TMP2=$TMP"

		# Mover fragmento. Lo pongo fichero a fichero para poder sacarlo por el log e ir informando al usuario del proceso de copia
		for recordFile in ${DIR_ORIGEN}/${TMP2}* ; do
		   echo "echo Copiando $recordFile a $DIR_DESTINO >> $LOGPROC" >> $SCRIPT
		   echo "cp $recordFile $DIR_DESTINO 2>> $LOGPROC" >> $SCRIPT
      done
      
		# Siguiente fragmento
		i=$(($i+1))
	done
	
	# Comprobar fragmentos compartidos

	# Eliminar ficheros temporales
   if [ $mover -eq 1 ]; then
    	i=0
    	while [ $i -lt $num_fmpg ]; do
    		# Nombre fragmento
    		TMP='$fmpg'${i}
    		eval "TMP2=$TMP"
    
    		# Mover fragmento
    		echo "rm -f ${DIR_ORIGEN}/${TMP2}*" >> $SCRIPT
    		echo "echo Borrado de ${DIR_ORIGEN}/${TMP2}* >> $LOGPROC" >> $SCRIPT
    
    		# Siguiente fragmento
    		i=$(($i+1))
    	done
    	echo "rm -f ${Cridfile}" >> $SCRIPT
    	echo "echo Borrado de ${Cridfile} >> $LOGPROC" >> $SCRIPT
	fi
	
	# Mover ficheros
	echo "echo Copia/Traspaso de Grabacion Finalizada >> $LOGPROC" >> $SCRIPT
	echo "date >> $LOGPROC" >> $SCRIPT
	cat $SCRIPT >> $LOG
	eval "(`cat $SCRIPT`) >> $LOG 2>> $LOG"
	
	rm -f $SCRIPT
	
	# Borrar fichero .refXML
   rm -f $Cachefile

	# Resultado OK
	enviar_xml_ok
else
   echo "ERROR: El directorio origen/destino no existen o no son accesibles." >> $LOGPROC
	# Resultado NO OK
	enviar_xml_err
fi
