#!/bin/bash
# pepper, (c) grupo SIESTA, 24-07-2007
#
# Script que realiza un reboot del sistema

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Ejecutar reboot
reboot.sh &

# Resultado OK
enviar_xml_ok
