#!/bin/bash
# jotabe, (c) Grupo SIESTA, 07-11-2007
#
# Restaurar grabacion (ficheros crid, fmpg, mpg, idx, midx)

# Obtener parametros
Cridfile=${QUERY_STRING%-*}
if [ ${Cridfile/*-force/OK} == OK ]; then
	Cridfile=${Cridfile%-*}
	force=1
else
	force=0
fi

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
LOG=/tmp/archivo_crid.log
SCRIPT=/tmp/archivo_crid.sh
CRIDS_FMPG=/tmp/crids_fmpg.txt
Cachefile=${Cache}/`basename $Cridfile .crid`.refXML

# Log del proceso
echo "`date` Restaurar crid: $Cridfile, Force: $force" >> $LOG
echo -n "" > $SCRIPT
echo -n "" > $CRIDS_FMPG

# Obtenemos carpeta de grabaciones
RecordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`

# Comprobar carpetas y fichero
if [ -d $RecordingFolder -a -d $ARCHIVO_GRABACIONES -a -f $Cridfile ]; then
	# Procesar fichero crid
	eval `www-tools crid2var ${Cridfile}`
	echo "Fichero: `basename ${Cridfile}` -> $Titulo ($num_fmpg)" >> $LOG

	# Mover crid
	echo "mv -f ${Cridfile} $RecordingFolder" >> $SCRIPT

	# Nombres fragmentos
	i=0
	while [ $i -lt $num_fmpg ]; do
		# Nombre fragmento
		TMP='$fmpg'${i}
		eval "TMP2=$TMP"

		# Mover fragmento
		echo "mv -f ${ARCHIVO_GRABACIONES}/${TMP2}* $RecordingFolder" >> $SCRIPT

		# Comprobar fragmento compartido
		cridsConFMPG.sh ${ARCHIVO_GRABACIONES} ${TMP2} 2>/dev/null >> $CRIDS_FMPG

		# Siguiente fragmento
		i=$(($i+1))
	done

	# Borrar fichero .refXML
	echo "rm -f $Cachefile" >> $SCRIPT

	# Comprobar fragmentos compartidos
	if [ `cat $CRIDS_FMPG | wc -l` -eq 1 ]; then
		# Mover ficheros
		cat $SCRIPT >> $LOG
		eval "(`cat $SCRIPT`) >> $LOG 2>> $LOG"

		# Resultado OK
		enviar_xml_ok
	else
		# Error: varios ficheros crid comparten fichero fmpg
		echo "Ficheros .fmpg compartidos por varios .crid" >> $LOG
		cat $CRIDS_FMPG >> $LOG

		# Comprobar modo forzado
		if [ $force -eq 1 ]; then
			# Mover ficheros
			echo "Modo force, mover ficheros" >> $LOG
			cat $SCRIPT >> $LOG
			eval "(`cat $SCRIPT`) >> $LOG 2>> $LOG"

			# Resultado OK
			enviar_xml_ok
		else
			# Resultado FALLO
			enviar_xml_fallo
		fi
	fi

	# Eliminar ficheros temporales
	rm -f $SCRIPT
	rm -f $CRIDS_FMPG
else
	# Resultado ERROR
	enviar_xml_err
fi
