#!/bin/bash
# pepper, (c) Grupo SIESTA, 03-12-2007
#
# Script que genera un fichero de comandos con las instrucciones necesarias para
# visualizar una grabación en el PC local mediante MPlayer

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login

# Procesar parametros get/post
eval "`proccgi $*`"

# Obtener parametros
host=$FORM_host
port=$FORM_port
Cridfile=$FORM_cridfile
user=$FORM_user
pwd=$FORM_pwd
mplayer=$FORM_mplayer
tmpdir_linux=`echo $FORM_temp | sed 's/\/$//'`
tmpdir_windows=`echo $FORM_temp | sed 's/\\\\$//'`
aspect=$FORM_aspect
so=$FORM_so
encurso=$FORM_encurso

# Por si el host viene con puerto, lo quitamos para el ftp y lo dejamos para el http
ftphost=`echo $host | cut -d":" -f1`

# Opciones de mplayer
mplayerOptions="-cache 2048 -quiet -noaspect -aspect $aspect -autosync 30 -framedrop -ni"

# Obtener carpeta de almacenamiento
recordingDir=`dirname $Cridfile`

# Guardar configuracion
echo "${mplayer}" > ${SERVER_ROOT}/cfg/.path_mplayer.txt
if [ $so -eq 0 ]; then
	echo "${tmpdir_linux}" > ${SERVER_ROOT}/cfg/.path_temp.txt
else
	echo "${tmpdir_windows}" > ${SERVER_ROOT}/cfg/.path_temp.txt
fi

# Procesar fichero crid
eval `www-tools crid2var ${Cridfile}`

# Log del proceso
echo "`date` Peticion visualizacion grabacion:
	$ftphost, $port, $Cridfile, ${fmpg0}*, $user, $pwd, $aspect, Titulo: $Titulo" >> /var/log/ver-crid.log

# Descargar fichero de visualizacion
echo "Content-type: application/octet-stream"
if [ $so -eq 0 ]; then
	# Fichero playlist
	plsfile=$tmpdir_linux/mplayer_temp_`date +%s`.pls

	# Linux/Unix
	echo "Content-Disposition: attachment; filename=ver_grabacion.sh"
	echo ""
	echo "#!/bin/sh"
	echo "rm -f $plsfile"
	echo "touch $plsfile"
	if [ "$encurso" = "NO" ]; then
		for mpg in ${recordingDir}/${fmpg0}*.mpg; do
			echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${mpg}\" >> $plsfile"
		done
	else
		i=0
		while [ $i -lt 40 ]; do
			if [ $i -lt 10 ]; then
				echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.00$i.mpg\" >> $plsfile"
			else
				echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.0$i.mpg\" >> $plsfile"
			fi
			i=$((i+1))
		done
	fi
	echo "$mplayer $mplayerOptions -playlist $plsfile"
else
	# Fichero playlist
	plsfile=$tmpdir_windows\\mplayer_temp_`date +%s`.pls

	# Windows
	echo "Content-Disposition: attachment; filename=visualizar_grabacion.cmd"
	echo ""
	echo "@ECHO OFF > $plsfile"
	if [ "$encurso" = "NO" ]; then
		for mpg in ${recordingDir}/${fmpg0}*.mpg; do
			echo "ECHO ftp://${user}:${pwd}@${ftphost}:${port}$mpg >> $plsfile"
		done
	else
		i=0
		while [ $i -lt 40 ]; do
			if [ $i -lt 10 ]; then
				echo "ECHO ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.00$i.mpg >> $plsfile"
			else
				echo "ECHO ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.0$i.mpg >> $plsfile"
			fi
			i=$((i+1))
		done
	fi
	echo "\"$mplayer\" $mplayerOptions -playlist $plsfile"
fi
