#!/bin/bash
# jotabe, (c) Grupo SIESTA, 10-01-2008
#
# Comprobacion mostrar login de usuario

# Configurar entorno
source www-setup.shi
source fweb.shi
LOG=/tmp/login.log

# Comprobar tipo de login
case $LOGIN_HTTP in
	cookie)
		# Login por cookie
		destino="/html/login.html"
		;;
	htpasswd)
		# Autentificacion por servidor web
		echo "`date` Autentificación htpasswd" >> $LOG
		destino="${PAGINA_INICIO_WEB}"
		;;
	nologin)
		# Login directo
		echo "`date` Login directo" >> $LOG
		destino="${PAGINA_INICIO_WEB}"
		;;
esac

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"${destino}\"
	</script>
</head>
</html>"
