#!/bin/bash
# by pepper, 17/04/2007
# El formato del archivo es usuario:password

echo content-type: text/html
echo
echo

CREDENTIALS=/var/etc/www-settings.txt

user=`cat ${CREDENTIALS} | grep USUARIO | cut -d"=" -f2 | cut -d":" -f1`
pwd=`cat ${CREDENTIALS} | grep USUARIO | cut -d"=" -f2 | cut -d":" -f2`

# check input data : GET or POST
case $REQUEST_METHOD in
	GET)
		# CGI Arguments are in QUERY_STRING
		;;

	POST)
		# First line from standard input contains CGI arguments
		read -r query_string
		# If QUERY_STRING is non-empty, append the string read from
		# standard input. This is useful for debugging purposes
		if [ "${QUERY_STRING}" != "" ]; then
			QUERY_STRING="${QUERY_STRING}&${query_string}"
		else
			QUERY_STRING=${query_string}
		fi
		;;
esac

#userlogin=`echo $QUERY_STRING | cut -d"-" -f1`
userlogin=`echo $QUERY_STRING | cut -d"&" -f1 | cut -d"=" -f2`
#pwdlogin=`echo $QUERY_STRING | cut -d"-" -f2`
pwdlogin=`echo $QUERY_STRING | cut -d"&" -f2 | cut -d"=" -f2 | sed 's/%40/@/g'`

if [ "$user" = "$userlogin" -a "$pwd" = "$pwdlogin" ]; then
    echo "`date` Login OK: $userlogin / $pwdlogin" >> /tmp/login.log
    echo "<html><head><title>Login OK</title>"
    echo "<script language=\"JavaScript\" src=\"/sincro/js/cookies.js\"></script>"
    echo "<script>"
    echo "setCookie(\"LOGGED\", new Date().getTime(), getExpire());"
    echo "</script></head>"
    echo "<body><script>document.location.href=\"/cgi-bin/sincro/pgmactualXML\"</script></body></html>"
else
    echo "`date` Login NOK: $userlogin / $pwdlogin" >> /tmp/login.log
    echo "<html><head><title>Login incorrect</title>"
    echo "<script>alert(\"Usuario/password incorrecto\"); document.location.href=\"/index.html\";</script>"
    echo "</head><body></body></html>"
fi
