#!/bin/sh
# Lemmi, 2006-07-11 -> GPL

allowed="cat df fdisk halt ls mp3shuffle ps reboot set-www"

source ../www-setup
. theme header_no_nav "Befehl ausführen" "Befehl ausführen" "Lemmi"

line=`httpd -d "$QUERY_STRING"`
cmd=${line// *}

if echo "$allowed" | grep -q "\b$cmd\b"
then

    cat <<- ---EOT---
	<h2>Befehl: <tt>`echo "$line"|sed 's/&/\&amp;/g;s/</\&lt;/g'`</tt></h2>
	<p>
	<pre style="background-color: #e0e0ff; padding: .3em">`$line 2>&1 | sed 's/&/\&amp;/g;s/</\&lt;/g'`</pre>
	---EOT---

else

    cat <<- ---EOT---
	Befehl: <tt>`echo "$line"|sed 's/&/\&amp;/g;s/</\&lt;/g'`</tt>
	<p>
	<span style="background-color: #ffd0d0; border-color: #a00000">
		Es werden nur erlaubte Befehle ausgeführt.</span>
	<p>
	Erlaubt Befehle: <tt>$allowed</tt>
	---EOT---

fi

. theme footer
