#!/bin/bash
# by pepper, 10-05-2007
#
# Script de descarga del fichero M750_TVLive.cmd

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login

# Procesar parametros get/post
eval "`proccgi $*`"

# Enviar cabecera
echo "Content-type: application/octet-stream"
echo "Content-Disposition: attachment; filename=M750_TVLive.cmd"
echo ""

# Enviar script
echo "\"$FORM_mplayer\" -framedrop -cache 2048 -aspect $FORM_aspect -quiet -slave rtp://$FORM_host:$FORM_port"
