#!/bin/sh
# Lemmi, m740av (at) cle-mens . de, 2006-10-08, GPL2

. def-lemmi.inc

fname="dump-info-`date +%F-%H%M%S`.tgz"

#--------------------------------------------------

function print_info()
{
    cat <<- ---EOT---

	<h2>Aktuellen Zustand sichern</h2>

	Um die Ferndiagnose zu vereinfachen, kann hier ein Archiv (.tgz) erzeugt
	und als Download gespeichert werden.
	Das Archiv enthält Kopien von mehreren Dateien, hauptsächlich LOG-Dateien,
	der Box und die Ausgaben einiger Kommandos als Dump.

	<p>
	Zur Sicherheit werden aus den Dateien <tt>/var/etc/settings.txt</tt> und
	<tt>/var/log/mount.log</tt> automatisch die Kennw&ouml;rter entfernt.

	<p>
	<b>Download:</b>
	<ul>
	<li><a href="$SCRIPT_NAME/$fname?download"><tt>dump-info-&lt;date+time>.tgz</tt><a>
	</ul>

	---EOT---
}

#--------------------------------------------------

if [[ "$QUERY_STRING" == "download" ]]
then

    cat <<- ---EOT---
	Content-Type: application/x-gzip
	Content-Disposition: attachment; filename="$fname"
	Expires: `date -R`

	---EOT---
    /sbin/dump-info --stdout

else

    html_begin "Dump-Info"
    print_info
    html_end

fi

