#!/usr/bin/awk -f 
# post2iso - convert http get/post output to ISO/ASCII charset
# Martin Ostermann 2005-08-23

function hex2int(c, n, d) {
	n=length(c); m=1; d=0	
	while ( n > 0 ) {
		d = d*16 + index( "0123456789ABCDEF", substr(c,m,1)) -1
		n=n-1; m=m+1
	}
	return d
}

BEGIN { RS = "%[[:alnum:]]{2}" }

{ gsub( "[+]", " ") }

{ if (RT == "")
		printf "%s", $0
	else 
		printf "%s%c", $0, hex2int(substr(RT,2))
}
