#!/bin/bash
# jotabe, (c) Grupo SIESTA, 28-08-2007
#
# Guarda la configuración de LCK

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
LCK_SETTINGS_FILE=/var/etc/LCK.cfg
TMP1=${LCK_SETTINGS_FILE}.temp
TMP2=${LCK_SETTINGS_FILE}.temp2

# Generar fichero con valores de parametros
get_maquina
if [ $MAQUINA = "GigaSet" ]; then
	httpd -d "${QUERY_STRING}" | sed 's/&/\n/g;s/=/ /g' > $TMP1
else
	echo "$QUERY_STRING" | sed 's/&/\n/g;s/%3A/:/g;s/=/ /g' > $TMP1
fi

# Recorrer fichero
sed_script=""
while read line; do
	if [ ${#line} -ne 0 ]; then
		if [ ${line:0:1} != "#" ]; then
			# Obtener nombre y valor parametro
			TMP=(`echo $line`)
			NombreParametro=${TMP[0]}
			ValorParametro0=${TMP[1]}
			TMP3=(`grep ^${NombreParametro} $TMP1`)
			ValorParametro=${TMP3[1]}
			if [ "Z$ValorParametro" != "Z$ValorParametro0" ]; then
				# Generar script de sustitucion
				[ ${#sed_script} -ne 0 ] && sed_script="${sed_script};"
				sed_script="${sed_script}s/$line/$NombreParametro $ValorParametro/g"
			fi
		fi
	fi
done < $LCK_SETTINGS_FILE

# Sustituir valores parametros y actualizar configuracion
if [ ${#sed_script} -ne 0 ]; then
	sed -e "$sed_script" $LCK_SETTINGS_FILE > $TMP2
	mv -f $TMP2 $LCK_SETTINGS_FILE
fi

# Eliminar ficheros temporales
rm -f $TMP1

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/box/configLCK\"
	</script>
</head>
</html>"
