#!/bin/bash
# jotabe, (c) Grupo SIESTA, 29-11-2007
#
# Guarda la configuración de SIESTA

# Configurar entorno
LocalBin=/usr/local/bin
source $LocalBin/siesta-setup.sh
source ../www-setup.shi
source ../fweb.shi

# Procesar parametros get/post
eval "`proccgi $*`"

# Recorrer parametros de respuesta
for PARAM_SIESTA in ${!FORM_*}; do
	# Obtener valor de parametro
	TMP='$'${PARAM_SIESTA}
	eval "TMP2=$TMP"
	# Modificar parametro
	eval "${PARAM_SIESTA:5}=\"${TMP2}\""
done

# Volcado nuevos parametros
source $LocalBin/siesta-dump-settings.shi

# Pasar parametros configuracion a www-settings.txt
./ss2ws

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/box/configSIESTA\"
	</script>
</head>
</html>"
