#!/bin/bash
# jotabe, (c) Grupo SIESTA, 24-08-2007
#
# Guarda la configuración de SIESTA

# Configurar entorno
LocalBin=/usr/local/bin
source $LocalBin/siesta-setup.sh
source ../www-setup.shi
source ../fweb.shi
TMP1=${SIESTA_SETTINGS_FILE}.temp
TMP2=/var/tmp/siesta-$$.tmp

# Generar fichero con valores de parametros
httpd -d "${QUERY_STRING}" | sed 's/&/\n/g' > $TMP1

# Leer valores parametros nuevos
scan-param $SIESTA_SETTINGS_CONF_FILE < $TMP1 > $TMP2
source $TMP2

# Eliminar ficheros temporales
rm -f $TMP1
rm -f $TMP2

# Volcado nuevos parametros
source $LocalBin/siesta-dump-settings.shi

# Pasar parametros configuracion a www-settings.txt
./ss2ws

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/box/configSIESTA\"
	</script>
</head>
</html>"
