#!/bin/bash
# Lemmi @ m740.info/forum, 2005-09-04 -> GPL
# jotabe, (c) Grupo SIESTA, 25-07-2007
#
# Explorador de archivos para gigaset

#--------------------------------------------------
# Accion view
# $1 flags
# $2 mime-type
# $3 view-cmd
#--------------------------------------------------
function view() {
	# Accion view
	action=view

	# Comprobar flags, 1º view
	if [ ${1/*v*/OK} = OK ]; then
		print_top "$PATH_INFO" "$1" ""
		echo "			<tr class=\"filaNormal\">"
		echo "				<td>"
		print_actions
		echo -n "<pre style=\"background-color:#FFEEE6; padding:.2em\" >"
		$3 "$PATH_INFO" | head -c 1000000 | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'
		echo "</pre>"
		print_actions
		echo "				</td>"
		echo "			</tr>"
		print_bottom
	# Comprobar download
	elif [ ${1/*s*/OK} = OK ]; then
		send $*
	# En ultimo lugar hexdump
	else
		hexdump $*
	fi
}

#--------------------------------------------------
# Accion hexdump
# $1 flags
# $2 mime-type
# $3 view-cmd
#--------------------------------------------------
function hexdump() {
	# Accion hexdump
	action=hexdump

	# Enviar contenido html
	print_top "$PATH_INFO" "$1" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	print_actions
	echo -n "<pre>"
	head -c 1000000 "$PATH_INFO" | hexdump16 | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'
	echo "</pre>"
	print_actions
	echo "				</td>"
	echo "			</tr>"
	print_bottom
}

#--------------------------------------------------
# Accion send
# $1 flags
# $2 mime-type
# $3 view-cmd
#--------------------------------------------------
function send() {
	echo "Content-type: $2"
	#realTotalBytes=(`wc -c $PATH_INFO`)
	#echo "Content-length: $realTotalBytes"
	echo "Expires: "`date -R`
	echo ""
	shift
	cat "$PATH_INFO"
}

#--------------------------------------------------
# Accion edit
# $1 flags
# $2 mime-type
# $3 view-cmd
#--------------------------------------------------
function edit() {
	info=(`ls -l "$PATH_INFO"`)
	if [ ${1/*e*/OK} = OK -a ${info[4]} -le 50000 ]; then
		print_top "$PATH_INFO" "$1" "$SCRIPT_NAME$PATH_INFO?write"
		echo "			<tr class=\"filaNormal\">"
		echo "				<td>"
		print_actions
		echo "<textarea wrap=\"virtual\" name=\"text\" rows=28 cols=82 maxlength=60000>"
		sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g' "${PATH_INFO}"
		echo "</textarea>"
		echo "					<br>"
		echo "					<input type=\"Submit\" value=\"Grabar\">"
		echo "					<input type=\"Reset\" value=\"Deshacer Cambios\">"
		print_actions
		echo "				</td>"
		echo "			</tr>"
		print_bottom
	else
		view $*
	fi
}

#--------------------------------------------------
# Accion write, datos fichero en POST
#--------------------------------------------------
function write() {
	# Guardar datos fichero
	# Con sed respeta formato pero a veces no encuentra final y se bloquea, fichero a 0
# 	sed 's/text=//;s/%0D//g' | post2iso > "${PATH_INFO}"
	# Con proccgi añade 0x0A en ultima linea (si no existe)
	eval "`proccgi $*`"
	echo "$FORM_text" > "${PATH_INFO}"

	# Si el fichero está bajo /var/etc, llamamos tambien a flash_archive, para grabar los cambios en la flash
	isFlash=`echo "${PATH_INFO}" | grep "/var/etc" | wc -l`
	if [ $isFlash -gt 0 ]; then
		echo "flash_archive write ${PATH_INFO}" >> /var/log/flash_archive.log
		flash_archive write ${PATH_INFO} >> /var/log/flash_archive.log 2>&1
		alert="Los cambios del fichero ${PATH_INFO} se han grabado de forma persistente en FlashRAM"
	fi

	# Accion view
	view $*
}

#--------------------------------------------------
# Accion delete
#--------------------------------------------------
function delete() {
	# Borrado fichero/carpeta
	if [ -d "$PATH_INFO" -a ! -L  "$PATH_INFO" ]; then
		rmdir "$PATH_INFO" > /dev/null 2>&1
	else
		rm -f "$PATH_INFO" > /dev/null 2>&1
	fi

	# Obtener carpeta contenedora del fichero
	PATH_INFO=`dirname $PATH_INFO 2>/dev/null`

	# Enviar redireccion html para mostrar carpeta
	http_header
	echo "<html>
	<head>
		<script type=\"text/javascript\">
			document.location.href=\"$SCRIPT_NAME$PATH_INFO\"
		</script>
	</head>
</html>"
}


#--------------------------------------------------
# Un bug en thttpd hace que si la url termina en / se ejecuta correctamente este script
# pero no obtiene el SCRIPT_NAME correcto. Se pone el valor correcto manualmente.
SCRIPT_NAME=/cgi-bin/box/show

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
source ./fshow.shi
alert=""

# Sanear PATH_INFO 
PATH_INFO=`echo $PATH_INFO | sed -e 's/\/*$//'`
[ "Z$PATH_INFO" = "Z" ] && PATH_INFO="/"

# Modo de llamada
mode="${QUERY_STRING%%=*}"

# Comprobar existencia fichero
if [ ! -e "$PATH_INFO" ]; then
	print_top "No encontrado $PATH_INFO" "" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	echo "					<p>Fichero no encontrado."
	echo "				</td>"
	echo "			</tr>"
	print_bottom
# Comprobar modo borrado
elif [ "Z$mode" = "Zdelete" ]; then
	delete
# Comprobar carpeta
elif [ -d "$PATH_INFO" ]; then
	print_top "$PATH_INFO" "" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	echo -n "<pre style=\"background-color: #FFEEE6; padding: .2em; font-family: \'Lucida Console\'; color: black;\">"
	# Comprobar maquina: M740, M750, PC
	get_maquina
	if [ "Z$MAQUINA" = "ZPC" ]; then
		ls -la "$PATH_INFO/" | tail -n +2 | awk -f $0.awk -v "nc_file=9" -v "col_file=42" -v "uri=$SCRIPT_NAME$PATH_INFO"
	else
		ls -la "$PATH_INFO/" | awk -f $0.awk -v "nc_file=9" -v "col_file=57" -v "uri=$SCRIPT_NAME$PATH_INFO"
	fi
	echo "</pre>"
	echo "				</td>"
	echo "			</tr>"
	print_bottom
# Comprobar fichero bloque
elif [ -b "$PATH_INFO" ]; then
	print_top "Fichero-Especial-Bloque $PATH_INFO" "" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	echo "					<p>Fichero especial de bloque con ID "`ls -l "$PATH_INFO" | awk '{printf("%s%s\n",$5,$6)}'`
	echo "				</td>"
	echo "			</tr>"
	print_bottom
# Comprobar fichero caracter
elif [ -c "$PATH_INFO" ]; then
	print_top "Fichero-Especial-Caracter $PATH_INFO" "" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	echo "					<p>Fichero especial de caracter con ID "`ls -l "$PATH_INFO" | awk '{printf("%s%s\n",$5,$6)}'`
	echo "				</td>"
	echo "			</tr>"
	print_bottom
# Comprobar fichero normal
elif [ ! -f "$PATH_INFO" ]; then
	print_top "Tipo desconocido $PATH_INFO" "" ""
	echo "			<tr class=\"filaNormal\">"
	echo "				<td>"
	echo "					<p>Tipo de fichero desconocido."
	echo "				</td>"
	echo "			</tr>"
	print_bottom
else
	# Obtener acccion, por defecto view
	[[ "$mode" = "send" \
	|| "$mode" = "hexdump" \
	|| "$mode" = "edit" \
	|| "$mode" = "write" \
	]] && action="$mode" || action=view

	# flags
	#	t--- : tar
	#	c--- : crid
	#   -e-- : edit possible
	#   --v- : view possible
	#   ---s : send instead of viewing

    case "$PATH_INFO" in
	#--------------------------------------------------------------------
	# file-type		action	flags	mime-type			view-cmd
	#--------------------------------------------------------------------
	*.tar.bz2)		$action t-v-	application/x-bzip2		"tar tjvf"	;;
	*.tar.gz|*.tgz)	$action t-v-	application/x-gzip		"tar tzvf"	;;
	*.bz2)			$action --v-	application/x-bzip2		bzcat		;;
	*.gz)			$action --v-	application/x-gzip		zcat		;;
	*.avi)			$action ----	video/x-msvideo						;;
	*.bmp)			$action ---s	image/bmp							;;
	*.crid)			$action c---	application/x-crid					;;
	*.gif)			$action ---s	image/gif							;;
	*.html|*.htm)	$action -e-s	text/html							;;
	*.jpeg|*.jpg)	$action ---s	image/jpeg							;;
	*.mpeg|*.mpg)	$action ---s	video/mpeg							;;
	*.idx)			$action ---s	application/x-idx					;;
	*.midx)			$action ---s	application/x-midx					;;
	*.fmpg)			$action ---s	video/mpeg							;;
	*.mpga|*.mp3)	$action ---s	audio/mpeg							;;
	*.png)			$action ---s	image/png							;;
	*.tar)			$action t---	application/x-tar		"tar tcf"	;;
	*.tiff|*.tif)	$action ---s	image/tiff							;;
	*.txt|*.ini)	$action -ev-	text/plain				cat			;;
	*.awk)			$action -ev-	text/plain				cat			;;
	*.crontab)		$action -ev-	text/plain				cat			;;
	*.sh)			$action -ev-	text/plain				cat			;;
	*.cfg)			$action -ev-	text/plain				cat			;;
	*.log)			$action -ev-	text/plain				cat			;;
	*.wav)			$action ----	audio/x-wav							;;
	*.wsw)			$action ----	application/x-wsw					;;
	*.zip)			$action ----	application/zip						;;
	rc.*|halt.*)	$action -ev-	text/plain				cat			;;
	*.*)			$action --v-	application/x-unknown	cat			;;
	*)				$action -ev-	application/x-unknown	cat			;;
    esac
fi
