#!/bin/bash
# jotabe, (c) Grupo SIESTA, 04-09-2007
#
# Pasar configuracion de siesta-settings.txt a www-settings.txt

# Configurar entorno
LocalBin=/usr/local/bin
source $LocalBin/siesta-setup.sh
FICHERO_WWW_SETTINGS=/var/etc/www-settings.txt

# Flag orden de grabaciones
case $SIESTA_ORDEN_GRABACIONES in
	time ) ORDEN_GRABACIONES=.time_sort;;
	serie ) ORDEN_GRABACIONES=.serie_sort;;
	* ) ORDEN_GRABACIONES=.time_sort;;
esac
rm -f $SIESTA_CACHE_HTTP/.time_sort
rm -f $SIESTA_CACHE_HTTP/.serie_sort
touch $SIESTA_CACHE_HTTP/$ORDEN_GRABACIONES

# Canales de parrilla por defecto
if [ "Z$SIESTA_CANALES_PARRILLA" != "Z" ]; then
	echo $SIESTA_CANALES_PARRILLA > $SIESTA_CACHE_HTTP/parrilla_channels.txt
fi

# Crear fichero www-settings.txt
cat <<- ---EOT--- >$FICHERO_WWW_SETTINGS
Cache=$SIESTA_CACHE_HTTP
EPG_PATH=$SIESTA_EPG_HTTP
USUARIO=$SIESTA_USUARIO_HTTP
MOSTRAR_MINI_IMG=$SIESTA_MOSTRAR_MINI_IMG
OBTENER_IMG_INET=$SIESTA_OBTENER_IMG_INET
DESCARGA_IMG=$SIESTA_ACTIVAR_DESCARGA_IMG
CACHE_EPG_LONG=$SIESTA_CACHE_EPG_LONG
ARCHIVO_GRABACIONES=$SIESTA_RUTA_ARCHIVO
---EOT---
