#!/bin/bash
# pepper, (c) Grupo SIESTA, 10-05-2007
#
# Script para la visualización de la TV en directo (necesita matar el wavebox)

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Procesar parametros get/post
eval "`proccgi $*`"
host=$FORM_host
port=$FORM_port
localPC=$FORM_ip
dvbstream=$FORM_dvbstream
mplayer=$FORM_mplayer
aspect=$FORM_aspect
freq=$FORM_freq
p1=$FORM_p1
p2=$FORM_p2
p3=$FORM_p3

# Detener procesos wavebox
pkill -9 inout_wdg
sleep 1
pkill -9 wavebox
pkill -9 play_backend
pkill -9 record_backend
sleep 1

# Iniciamos el servidor de streaming
if [ -f $dvbstream ]; then
	# Ejecutar dvbstream
	echo "$dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3 &" >> /var/log/tvlive.log
	$dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3 &

	# Resultado OK
	enviar_xml_ok
else
	echo "ERROR: dvbstream no se encuentra en el path" >> /var/log/tvlive.log

	# Resultado NO OK
	enviar_xml_err
fi
