#!/bin/bash
# jotabe, (c) Grupo SIESTA, 28-08-2007
#
# Ver descripcion parametros SIESTA

# Configurar entorno
source ../fweb.shi

# Enviar documento html
html_doc_start "M750T - Parámetros SIESTA" "" "--n---b-"

# Respuesta html
html_top "Parámetros SIESTA" "" ""

# Volcado descripciones parametros
echo "				<br>
				<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
					<tr>
						<td align=\"left\">
							<pre>"

cat siesta-settings.desc

# Final html
echo "							</pre>
						</td>
					</tr>
				</table>"
html_doc_end
