#!/bin/bash
# jotabe, (c) Grupo SIESTA, 11-01-2008
#
# Ver descripcion parametros LCK

# Configurar entorno
source ../www-setup.shi
source fweb.shi

# Enviar documento html
html_doc_start "M750T - Parámetros LCK" "" "--n---b-"

# Respuesta html
echo "<body bgcolor=\"#FFFFFF\">
<form name=\"form_m750\" method=\"get\">
	<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
		<tr>
			<td align=\"center\">
				<font class=\"titPag\">M750T EPG</font>
				<br>
				<font class=\"subTitPag\">Parámetros LCK</font>
			</td>
		</tr>
	</table>
	<table width=\"98%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
		<tr>
			<td>
				<br>
				<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
					<tr>
						<td align=\"left\">
							<pre>"

# Volcado descripciones parametros
cat $SERVER_ROOT/docs/lck-settings.desc

# Final html
echo "							</pre>
						</td>
					</tr>
				</table>"
html_doc_end no
