#!/bin/bash
source ../www-setup
. theme header "Cache neu aufbauen" "Cache wird neu aufgebaut" MartinO 300

n=1; 
for f in /usb/Video/*.crid ; do 
	echo "$n<br>"; ./title $f >/dev/null; n=$(($n+1))
done

cat <<EOF
Der Cache f&uuml;r die CRID Inhalte wurde aufgebaut. 

EOF

. theme footer 2005-08-29
