#!/bin/bash 
# Martin Ostermann, 2005-08-21
# Modified by pepper to return XML, 25/04/2007

source ../www-setup
if [ $# = 1 ]; then
	Cridfile=$1
else
	Cridfile=$QUERY_STRING
fi
Basename=`basename $Cridfile .crid`

declare -a Crid0
declare -a Crid1
declare -a Crid2
declare -a Crid3

Crid0=( `hexdump -n 50 -e '11/4 "%d \n" 1/2 "%d \n" 1/4 "%d \n" ' $Cridfile ` )
c1=${Crid0[12]}
s1=$(( 50 + $c1 ))
n1=8
serieId=${Crid0[10]}

Title=`hexdump -v -s $(($s1-$c1)) -n $c1 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br\/>/g' `
Begin=${Crid0[4]}
End=${Crid0[5]}

Crid1=( `hexdump -s $s1 -n $n1 -e "2/4 \"%d \n\" " $Cridfile ` )
c2=${Crid1[1]}
s2=$(( $s1+$n1+$c2 ))
fmpg=`hexdump -v -n $c2 -s $(($s1+$n1)) -e '"%c"' $Cridfile | sed -e 's/&/&amp;/g'`

c3=$c2
s3=$s2

f=${Crid1[0]}
while [ $f != 0 ] ; do
	n2=24
	Crid2=( `hexdump -s $s2 -n $n2 -e "6/4 \"%d \n\" " $Cridfile `)
	c3=${Crid2[5]}
	s3=$(( $s2+$n2+$c3 ))
	s2=$s3
	c2=$c3
	f=$(($f-1))
done

if true ; then
	n3=4
	Crid3=( `hexdump -s $s3 -n $n3 -e "1/4 \"%d \n\" " $Cridfile `)
	c4=${Crid3[0]}
	s4=$(( $s3+$n3+$c4 ))
	n4=4

	if [ $c3 != 0 ]; then
		EPGshort=`hexdump -v -s $(($s3-$c3)) -n $c3 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br\/>/g' `
	fi
	if [ $c4 != 0 ]; then
		EPGlong=`hexdump -v -s $(($s4-$c4)) -n $c4 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br\/>/g' `
	fi
fi

SenderInfo=`grep ${Basename: -5}$ /var/etc/services.txt`
SenderName=`echo ${SenderInfo:0:20} | sed -e 's/&#5;//g' -e 's/&#138;/<br>/g'`
DiaSemana=([1]="Lun" [2]="Mar" [3]="Mie" [4]="Jue" [5]="Vie" [6]="Sab" [7]="Dom")
ds=`awk "BEGIN {print strftime( \"%u\" , $Begin) }"`
dateFormatIni=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $Begin) }"`
dateFormatIni="$dateFormatIni, ${DiaSemana[ds]}"
ds=`awk "BEGIN {print strftime( \"%u\" , $End) }"`
dateFormatFin=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $End) }"`
dateFormatFin="$dateFormatFin, ${DiaSemana[ds]}"

echo "<CHANNEL_NAME>$SenderName</CHANNEL_NAME>"
awk "BEGIN {print \"<INIT_TIME>$dateFormatIni</INIT_TIME><END_TIME>$dateFormatFin</END_TIME><DURATION>\" ($End-$Begin)/60 \"</DURATION><UTC_TIME>$Begin</UTC_TIME>\" }"
echo "<TITLE>$Title</TITLE>"
echo "<EPG_SHORT>$EPGshort</EPG_SHORT>"
echo "<EPG_LONG>$EPGlong</EPG_LONG>"
echo "<SERIE_ID>$serieId</SERIE_ID>"
echo "<CRIDFILE>$Cridfile</CRIDFILE>"
echo "<FMPG>$fmpg</FMPG>"
