#!/bin/bash 
# by pepper, 26/04/2007
# Script que elimina una grabación a partir del fichero .crid

source ../www-setup
if [ $# = 1 ]; then
    Cridfile=$1
else
    Cridfile=$QUERY_STRING
fi

echo "Borrar grabación de Crid: $Cridfile" >> /tmp/delete_recording.log
declare -a Crid0
declare -a Crid1
declare -a Crid2
declare -a Crid3

Crid0=( `hexdump -n 50 -e '11/4 "%d \n" 1/2 "%d \n" 1/4 "%d \n" ' $Cridfile ` )
c1=${Crid0[12]}
s1=$(( 50 + $c1 ))
n1=8

Crid1=( `hexdump -s $s1 -n $n1 -e "2/4 \"%d \n\" " $Cridfile ` )
c2=${Crid1[1]}
s2=$(( $s1+$n1+$c2 ))
fmpg=`hexdump -v -n $c2 -s $(($s1+$n1)) -e '"%c"' $Cridfile`
echo "fmpg: $fmpg" >> /tmp/delete_recording.log

fmpgBase=`basename $fmpg .fmpg`
recordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`

if [ -d $recordingFolder ]; then 
    echo "rm -f $recordingFolder/$fmpgBase*" >> /tmp/delete_recording.log
    echo "rm -f $Cridfile" >> /tmp/delete_recording.log
    rm -f $recordingFolder/$fmpgBase* >> /tmp/delete_recording.log 2>> /tmp/delete_recording.log
    rm -f $Cridfile >> /tmp/delete_recording.log 2>> /tmp/delete_recording.log
    echo Content-type: text/xml
    echo ""
    echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
    echo "<M750><RESULT>1</RESULT></M750>"
else
    echo Content-type: text/xml
    echo ""
    echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
    echo "<M750><RESULT>0</RESULT></M750>"
fi
