#!/bin/bash
# pepper, (c) Grupo SIESTA, 25-04-2007
#
# Mostrar informacion sobre grabacion (fichero crid)
# detalle-crid?crid&utc

# Obtener parametro
Cridfile=`echo $QUERY_STRING | cut -d"&" -f1`

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login

# Enviar documento xml
xml_doc "/xsl/criddetail.xsl"

# Resultado xml
echo "<M750>
	<RECORD_DETAIL>"

# Procesar resultado
if [ -f $Cridfile ]; then
	# Procesar fichero crid
	./crid2xml.sh $Cridfile
else
	# Error fichero crid no encontrado
	echo "		<ERROR>La fichero de grabación $Cridfile no se encuentra.</ERROR>"
fi

# Final xml
echo "	</RECORD_DETAIL>
</M750>"
