#!/bin/bash 
# by pepper, 11/05/2007

# Ejecutamos el script con baja prioridad
renice 20 $$ > /dev/null

FMPGS_FILE=/tmp/fmpg_files.tmp
TSFILES=/tmp/tshift_files.tmp

rm -f $FMPGS_FILE
rm -f $TSFILES

Recordings=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt` 
if [ -d $Recordings ]; then
    haycrid=`ls -l $Recordings/*.crid 2> /dev/null | wc -l`
    touch $FMPGS_FILE
    if [ $haycrid -gt 0 ]; then
        for Cridfile in $Recordings/*.crid ; do
    		declare -a Crid0
            declare -a Crid1
            
            Crid0=( `hexdump -n 50 -e '11/4 "%d \n" 1/2 "%d \n" 1/4 "%d \n" ' $Cridfile ` )
            c1=${Crid0[12]}
            s1=$(( 50 + $c1 ))
            n1=8
            Crid1=( `hexdump -s $s1 -n $n1 -e "2/4 \"%d \n\" " $Cridfile ` )
            c2=${Crid1[1]}
            s2=$(( $s1+$n1+$c2 ))
            fmpg=`hexdump -v -n $c2 -s $(($s1+$n1)) -e '"%c"' $Cridfile | sed -e 's/&/&amp;/g'`
            echo $fmpg >> $FMPGS_FILE
        done
    fi
    for fmpgfile in $Recordings/*.fmpg ; do
        fmpg=`basename $fmpgfile`
        ists=`grep $fmpg $FMPGS_FILE | wc -l`
        if [ $ists -eq 0 ]; then
            echo $fmpgfile >> $TSFILES
        fi
    done
    if [ -f $TSFILES ]; then
        sort $TSFILES | tail -1
    fi
fi
