#!/bin/bash 
# by pepper

if [ $# != 0 ]; then
	Recording=$1
	Cridfile=$2
else
	Recording=`echo $QUERY_STRING | cut -d"-" -f1`
	Cridfile=`echo $QUERY_STRING | cut -d"-" -f2`
fi

RECS_FILE=/data/RA_FILE
SERIES_FILE=/data/SM_FILE

num=`grep $Recording $RECS_FILE | cut -d" " -f 1`
gIni=`grep $Recording $RECS_FILE | cut -d" " -f 8`
gIni=$((gIni/60))
gFin=`grep $Recording $RECS_FILE | cut -d" " -f 9`
gFin=$((gFin/60))
serieFlag=`grep $Recording $SERIES_FILE | wc -l`

n=1
sint=1
found=0
while read line
do
    if [ $found -eq 0 ]; then
        # Saltamos la primera linea
        if [ $n -gt 1 ]; then
            # la segunda linea contiene el numero de grabaciones del Sintonizador 1
            if [ $n -eq 2 ]; then
                numRecs=$line
                numRecs=$((numRecs+4))
            else
                #Comprobamos si ya hemos leído todas las grabaciones del sintonizador
                if [ $n -eq $numRecs ]; then
                    numRecsNew=$line
                    numRecs=$(($numRecs+$numRecsNew+1))
                    sint=2
                else
                    nRec=`echo $line | cut -d" " -f6`
                    if [ "$nRec" != "" ]; then
                        if [ $nRec -eq $num ]; then
                            echo Content-type: text/xml
                            echo ""
                            echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
                            echo "<?xml-stylesheet type=\"text/xsl\" href=\"/sincro/recordetail.xsl\"?>"
                            echo "<M750><RECORDING_DETAIL>"
                            echo "<NUM_REC>$num</NUM_REC><GUARDA_INI>$gIni</GUARDA_INI><GUARDA_FIN>$gFin</GUARDA_FIN><SINT>$sint</SINT><SERIE>$serieFlag</SERIE>"
                            ./cridXML $Cridfile
                            echo "</RECORDING_DETAIL></M750>"
                            found=1
                        fi
                    fi
                fi
            fi
        fi
    fi
    n=$((n+1))
done < $RECS_FILE