#!/bin/bash 
# Martin Ostermann, 2005-08-21
# Modified by pepper to return XML, 25/04/2007

source ../www-setup
if [ $# = 1 ]; then
	Cridfile=$1
else
	Cridfile=$QUERY_STRING
fi

echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<?xml-stylesheet type=\"text/xsl\" href=\"/sincro/criddetail.xsl\"?>"
echo "<M750><RECORD_DETAIL>"
./cridXML $Cridfile
echo "</RECORD_DETAIL></M750>"
