#!/bin/bash 
# (c) Grupo SIESTA, 06-08-2007
#
# Devolver grabaciones pendientes

# Procesar carpeta .timer
./lista-crid2xml.sh /data/.timer TIMER timer.xsl
# ./lista-crid2xml.sh /var/cache TIMER timer.xsl
