#!/bin/bash
# pepper, (c) Grupo SIESTA, 03-12-2007
#
# Script que genera un fichero de comandos con las instrucciones necesarias para
# visualizar una grabación en el PC local mediante MPlayer

# Configurar entorno
source ../www-setup.shi

# Procesar parametros get/post
eval "`proccgi $*`"

# Obtener parametros
host=$FORM_host
port=$FORM_port
Cridfile=$FORM_cridfile
user=$FORM_user
pwd=$FORM_pwd
mplayer=$FORM_mplayer
tmpdir=$FORM_temp
aspect=$FORM_aspect
so=$FORM_so
encurso=$FORM_encurso

# Por si el host viene con puerto, lo quitamos para el ftp y lo dejamos para el http
ftphost=`echo $host | cut -d":" -f1`

# Procesar fichero crid
eval `www-tools crid2var ${Cridfile}`

# Opciones de mplayer
mplayerOptions="-cache 2048 -quiet -noaspect -aspect $aspect -autosync 30 -framedrop -ni"

# Obtener carpeta de almacenamiento
recordingDir=`dirname $Cridfile`

# Log del proceso
echo "`date` Peticion visualizacion grabacion:
	$ftphost, $port, $Cridfile, ${fmpg0}*, $user, $pwd, $aspect, Titulo: $Titulo" >> /tmp/view_video.log

# Descargar fichero de visualizacion
echo "Content-type: application/octet-stream"
if [ $so -eq 0 ] ; then
	# Fichero playlist
	plsfile=$tmpdir/mplayer_temp_`date +%s`.pls

	#echo Linux/Unix
	echo "Content-Disposition: attachment; filename=ver_grabacion.sh"
	echo ""
	echo "#!/bin/sh"
	echo "rm -f $plsfile"
	echo "touch $plsfile"
	if [ "$encurso" = "NO" ]; then
		for mpg in ${recordingDir}/${fmpg0}*.mpg; do
			echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${mpg}\" >> $plsfile"
		done
	else
		i=0
		while [ $i -lt 40 ]; do
			if [ $i -lt 10 ]; then
				echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.00$i.mpg\" >> $plsfile"
			else
				echo "echo \"ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.0$i.mpg\" >> $plsfile"
			fi
			i=$((i+1))
		done
	fi
	echo "$mplayer $mplayerOptions -playlist $plsfile"
else
	# Fichero playlist
	plsfile=$tmpdir\\mplayer_temp_`date +%s`.pls

	#echo Windows
	echo "Content-Disposition: attachment; filename=visualizar_grabacion.cmd"
	echo ""
	echo "@echo off > $plsfile"
	if [ "$encurso" = "NO" ]; then
		for mpg in ${recordingDir}/${fmpg0}*.mpg; do
			echo "echo ftp://${user}:${pwd}@${ftphost}:${port}$mpg >> $plsfile"
		done
	else
		i=0
		while [ $i -lt 40 ]; do
			if [ $i -lt 10 ]; then
				echo "echo ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.00$i.mpg >> $plsfile"
			else
				echo "echo ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}.0$i.mpg >> $plsfile"
			fi
			i=$((i+1))
		done
	fi
	echo "\"$mplayer\" $mplayerOptions -playlist $plsfile"
fi
