#!/bin/bash
# (c) Grupo SIESTA, 12-11-2007
#
# Devolver lista de grabaciones realizadas
# ver-lista-grabaciones?[serie&dir|time&dir]

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
USB_DISK=/pvr/media/USB-HDD
USB_DISK_REALPATH=/var/media/USB-HDD

# Obtener parametros
case ${QUERY_STRING} in
	serie*)
		rm -f ${SERVER_ROOT}/cfg/.time_sort
		touch ${SERVER_ROOT}/cfg/.serie_sort
		;;
	time*)
		touch ${SERVER_ROOT}/cfg/.time_sort
		rm -f ${SERVER_ROOT}/cfg/.serie_sort
		;;
esac
Recordings=`echo ${QUERY_STRING} | cut -d"&" -f2`

# Obtener orden
[ -f ${SERVER_ROOT}/cfg/.serie_sort ] && orden=serie || orden=time

# Obtener carpeta de grabaciones
RecordingFolder=`awk '/DeviceRecordingFolder/ {print $2}' /var/etc/settings.txt`
[ ${#Recordings} -eq 0 ] && Recordings=$RecordingFolder

# Comprobacion USB-HDD/PCx montado
info=""
error_folder=""
case ${Recordings} in
	OFF )
		info="No está definida la carpeta de grabaciones."
		;;
	${USB_DISK}/* | ${USB_DISK_REALPATH}/* )
		USB_MOUNTED=`grep ${USB_DISK_REALPATH} /proc/mounts | wc -l`
		[ ${USB_MOUNTED} -eq 0 ] && error_folder="al disco duro."
		;;
	/pvr/media/PC[1-5]/* | /var/media/PC[1-5]/* )
		PCx=${Recordings:13:1}
		PC_MOUNTED=`grep /var/media/PC${PCx} /proc/mounts | wc -l`
		[ ${PC_MOUNTED} -eq 0 ] && error_folder="a la carpeta compartida /pvr/media/PC${PCx}"
		;;
esac
[ ${#error_folder} -ne 0 ] && info="No se puede acceder a la carpeta de grabaciones realizadas porque no hay acceso ${error_folder}"

# Comprobar carpeta y nº de grabaciones
if [ ${#info} -eq 0 ]; then
	# Comprobar carpeta de grabaciones
	if [ ! -d ${Recordings} ]; then
		info="No existe la carpeta $Recordings
			<br><br>
			Revise la configuración de la carpeta de grabaciones de su gigaset."
	# Contar nº de grabaciones
	else
		numCrids=`ls -la $Recordings/*.crid 2>/dev/null | wc -l`
		[ $numCrids -eq 0 ] && info="No existe ninguna grabación en la carpeta $Recordings"
	fi
fi

# Mostrar error o procesar carpeta
if [ ${#info} -ne 0 ]; then
	# Enviar documento html
	html_doc_start "M750T - Grabaciones Realizadas" "" "-----b-"
	html_top "Grabaciones Realizadas" "" "" ""
	print_aviso_info "${info}"
else
	# Proxima carpeta a usar para lista de grabaciones
	carpeta_ver=/var/media/PC1/Video
	[ -f ${SERVER_ROOT}/cfg/.carpeta_ver.txt ] && carpeta_ver=`cat ${SERVER_ROOT}/cfg/.carpeta_ver.txt`
	[ "Z$Recordings" != "Z$RecordingFolder" -a "Z$Recordings" != "Z$carpeta_ver" ] && carpeta_ver=$Recordings

	# Guardar proxima carpeta
	echo "$carpeta_ver" > ${SERVER_ROOT}/cfg/.carpeta_ver.txt

	# Procesar carpeta de grabaciones
	./lista-crid2xml.sh $Recordings record $orden $carpeta_ver
fi
