#!/bin/bash
# pepper, (c) Grupo SIESTA, 06-06-2007
#
# Visualizar contenido fichero SM_FILE

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
source ../box/fshow.shi
FICHERO=/data/SM_FILE

# Ajustar variables para script show
SCRIPT_NAME=/cgi-bin/box/show
PATH_INFO=${FICHERO}
action="view"
flags="-ev-"

# Enviar documento html
print_top ${FICHERO} ${flags} ""
echo "			<tr>"
echo "				<td class=\"filaNormal\">"
print_actions
echo "					<pre style=\"background-color:#FFEEE6; padding:.2em\">"

# Procesar fichero
cat ${FICHERO} \
| sed -e 's/Series_ID/<hr width="100%" size="2"><font color="#0000FF" style="font-weight: bolder;">&<\/font>/g' \
| sed -e 's/EPG_title/<font color="#0000FF" style="font-weight: bolder;">&<\/font>/g'

# Final html
echo "					</pre>"
print_actions
echo "				</td>"
echo "			</tr>"
print_bottom
