#!/bin/bash
# pepper, jotabe, (c) Grupo SIESTA, 09-01-2008
#
# Validacion de login de usuario
# Formato de $USUARIO -> usuario:password

# Configurar entorno
source www-setup.shi
source fweb.shi
user=`echo ${USUARIO} | cut -d":" -f1`
pwd=`echo ${USUARIO} | cut -d":" -f2`
LOG=/var/log/login.log

# Procesar parametros get/post
eval "`proccgi $*`"

# Enviar cabecera http
http_header

# Comprobar login
if [ "$user" = "$FORM_uid" -a "$pwd" = "$FORM_pwd" ]; then
	# Login correcto
	echo "`date` Login OK: $FORM_uid / $FORM_pwd / $REMOTE_ADDR / $HTTP_USER_AGENT" >> $LOG
	# Respuesta html
	echo "<html>
<head>
	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>
	<script type=\"text/javascript\" src=\"/js/cookies.js\"></script>
	<script type=\"text/javascript\">
		setCookie(\"M750_LOGIN\", \"${LOGIN_COOKIE}\", null, \"/\");
	</script>
	<title>Login OK</title>
</head>
<body>
	<script type=\"text/javascript\">
		document.location.href=\"${PAGINA_INICIO_WEB}\";
	</script>
</body>
</html>"

else
	# Login incorrecto
	echo "`date` Login NOK: $FORM_uid / $FORM_pwd / $REMOTE_ADDR / $HTTP_USER_AGENT" >> $LOG
	# Respuesta html
	echo "<html>
<head>
	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>
	<title>Login incorrecto</title>
</head>
<body>
	<script type=\"text/javascript\">
		alert(\"Usuario/contraseña incorrecto\");
		document.location.href=\"/index.html\";
	</script>
</body>
</html>"
fi
