#!/bin/sh
# by pepper, 24/04/2007
# Script de cambio de canal. Válido para canales de 0..99

if [ "$QUERY_STRING" != "" ]; then
    echo "sim 0 00 TV wer_server" > /dev/tcp/localhost/8765
    usleep 300000
    tecla=`echo $QUERY_STRING | cut -d"-" -f1`
    if [ $tecla -gt 9 ]; then
        tecla1=`echo $tecla | cut -b1-1`
        tecla2=`echo $tecla | cut -b2-2`
        echo "sim 0 00 $tecla1 wer_server" > /dev/tcp/localhost/8765
        usleep 300000
        echo "sim 0 00 $tecla2 wer_server" > /dev/tcp/localhost/8765
    else
        echo "sim 0 00 $tecla wer_server" > /dev/tcp/localhost/8765
    fi
fi
echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<M750><RESULT>OK</RESULT></M750>"
