#!/bin/bash
# Lemmi, 2006-07-11 -> GPL
# pepper, jotabe, (c) Grupo SIESTA, 09-01-2008
#
# Ejecucion de comandos linux en gigaset

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
LOG=/var/log/cmd.log
pie_botones="no"
cmd_permitidos=":estado.sh:picctl:cat:df:fdisk:halt:ls:ps:reboot.sh:grep:wc:touch:echo:cp:crontab:tar:ln:dos2unix:kill:pkill:bunzip2:netstat:traceroute:unzip:wget"

# Procesar parametros get/post
eval "`proccgi $*`"

# Obtener comando para ejecutar
line=$FORM_command
cmd_print=`echo "$line" | sed 's/&/\&amp;/g;s/</\&lt;/g'`
cmd=`basename ${line// *} 2>/dev/null`

# Enviar documento html
html_doc_start "M750T - Ejecución de comandos" "" "-----b-"

# Respuesta html
html_top "Ejecución de comandos" "" "" ""
echo "				<br>
				<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
					<tr>
						<td colspan=\"2\" class=\"txtNegrita\">Comando a ejecutar:</td>
					</tr>
					<tr>
						<td colspan=\"2\" class=\"txtNegrita\" height=\"10\"></td>
					</tr>
					<tr>
						<td class=\"txtNormal\">
							<input type=\"text\" name=\"command\" id=\"command\" size=\"64\" maxlength=\"128\" class=\"cajaPlana\" value=\"$cmd_print\">&nbsp;&nbsp;
							<input type=\"Submit\" value=\"Ejecutar\">
							<script type=\"text/javascript\">document.getElementById('command').focus();</script>
							<br>&nbsp;
						</td>
					</tr>
				</table>
				<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
					<tr>
						<td>"

# Comprobar comando
if [ "Z${cmd}" != "Z" ]; then
	# Guardar log
	echo "`date` -> $line" >> $LOG

	# Comprobar comando permitido
	echo "${cmd_permitidos}" | grep -q ":${cmd}:"
	if [ $? -eq 0 ]; then
		# Devolver resultado comando
		echo "							<h2>Resultado: <tt>$cmd_print</tt></h2>
							<p>
							<pre style=\"background-color: #FFEEE6; padding: .3em\">`eval $line 2>&1 | sed 's/&/\&amp;/g;s/</\&lt;/g'`</pre>"

		# Poner botones en pie de pagina
		pie_botones="si"
	else
		# Comando no permitido
		echo "							<h2>Comando: <tt>$cmd_print</tt></h2>
							<p>
							<span style=\"background-color: #FFEEE6; border-color: #a00000\">El comando especificado no está permitido.</span>
							<p>
							Comandos permitidos: <tt>`echo ${cmd_permitidos} | sed 's/:/ /g'`</tt>"
	fi
fi

# Final html 
echo "						</td>	
					</tr>
				</table>"
html_doc_end $pie_botones
