#!/bin/sh
# Lemmi, 2006-07-11 -> GPL
# Modified by pepper to run in the M750T

allowed="cat df fdisk halt ls ps reboot grep wc touch echo cp crontab tar ln dos2unix kill pkill bunzip2 netstat traceroute unzip wget"

source ../www-setup

line=`httpd -d "$QUERY_STRING" | sed 's/^command=//g'`
echo "$line" >> /tmp/cmd.log
cmd=${line// *}

echo Content-type: text/html
echo ""

cat <<-EOF
<html>
  <title>M750T - Ejecución de comandos</title>
  <meta http-equiv="refresh" content="600">
  <link href="/sincro/img/m740.ico" rel="shortcut icon"></link>
  <link href="/sincro/css/estilos.css" rel="stylesheet" type="text/css"></link>
  <script language="JavaScript" src="/sincro/js/ajax.js"></script>
  <script language="JavaScript" src="/sincro/js/navigator.js"></script>
  <script language="JavaScript" src="/sincro/js/controlenviar.js"></script>
  <script language="JavaScript" src="/sincro/js/fechasOp.js"></script>
  <script language="JavaScript" src="/sincro/js/botones.js"></script>
  <body bgcolor="#FFFFFF" onload="initFechas(); crearHrNow();">
    <form name="formulario">
    <div align="center"><p><font class="titPag">M750T EPG</font></p></div>
    <div align="center"><font class="subTitPag">Ejecución de comandos</font></div>
    <script language="JavaScript">barra_botones();</script>
EOF

if echo "$allowed" | grep -q "\b$cmd\b"
then
    cat <<- ---EOT---
	<h2>Comando: <tt>`echo "$line"|sed 's/&/\&amp;/g;s/</\&lt;/g'`</tt></h2>
	<p>
	<pre style="background-color: #FFEEE6; padding: .3em">`$line 2>&1 | sed 's/&/\&amp;/g;s/</\&lt;/g'`</pre>
	---EOT---
else

    cat <<- ---EOT---
	Comando: <tt>`echo "$line"|sed 's/&/\&amp;/g;s/</\&lt;/g'`</tt>
	<p>
	<span style="background-color: #FFEEE6; border-color: #a00000">
		El comando especificado no está permitido.</span>
	<p>
	Comandos permitidos: <tt>$allowed</tt>
	---EOT---
fi

cat <<-EOF
<script language="JavaScript">barra_botones();</script>
</form>
</body>
</html>
EOF
