#!/bin/bash
# jotabe, (c) Grupo SIESTA, 24-08-2007
#
# Configuracion SIESTA

#--------------------------------------------------
# Generar indice de descripciones parametros
#--------------------------------------------------
function gen_ix_desc() {
	# Prepara busqueda
	param="#PARAMETRO: "
	n=1
	start=1
	found=0

	# Recorrer fichero descripciones
	while read lin; do
		# Buscar parametro
		if [ "Z${lin:0:12}" = "Z$param" ]; then
			# Comprobar descripcion anterior
			[ $found -eq 1 ] && echo ",$((n-start-2))"
			# Nombre parametro
			par=`echo "$lin" | cut -d" " -f2`
			echo -n ":$par:,$n"
			start=$n
			found=1
		fi

		# Avanzar linea
		n=$((n+1))
	done < $SIESTA_SETTINGS_DESC_PARAM > $SIESTA_SETTINGS_DESC_PARAM_IX

	# Comprobar ultima descripcion
	[ $found -eq 1 ] && echo ",$((n-start-2))" >> $SIESTA_SETTINGS_DESC_PARAM_IX
}

#--------------------------------------------------
# Obtener descripcion parametro
# $1 Nombre parametro
#--------------------------------------------------
function desc_parametro() {
	# Buscar datos indice
	start=`grep ":$1:" $SIESTA_SETTINGS_DESC_PARAM_IX | head -1 | cut -d"," -f2`
	num_lines=`grep ":$1:" $SIESTA_SETTINGS_DESC_PARAM_IX | head -1 | cut -d"," -f3`
	# Extraer descripcion
	if [ "Z$start" != "Z" -a "Z$num_lines" != "Z" ]; then
		echo -n "<pre>"
		head -q -n $((start+num_lines-1)) $SIESTA_SETTINGS_DESC_PARAM | tail -q -n $num_lines
		echo "</pre>"
	fi
}


# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
VER_DESCRIPCIONES=0
SIESTA_SETTINGS_CONF_FILE=/etc/siesta-settings.conf
SIESTA_SETTINGS_FILE=/var/etc/siesta-settings.txt
SIESTA_SETTINGS_DESC_PARAM=siesta-settings.desc
SIESTA_SETTINGS_DESC_PARAM_IX=/tmp/siesta-settings.desc.ix

# Enviar documento html
html_doc_start "M750T - Configuración SIESTA" "" "-an-e-b-" "
function guardar() {
	mostrarMensajeProceso();
	document.forms['form_m750'].submit();
}"

# Respuesta html
html_top "Configuración SIESTA" "" "/cgi-bin/box/saveConfigSIESTA"

#Obtener fecha configuracion
FECHA_CFG=`grep "Fecha configuracion:" $SIESTA_SETTINGS_FILE`
[ ${#FECHA_CFG} -ne 0  ] && echo "				<br>
				<table width=\"50%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">
					<tr>
						<td align=\"center\" bgcolor=\"#ffb310\" class=\"titTabla\" height=\"20\">
							${FECHA_CFG}
						</td>
					</tr>
				</table>"

# Generar indice de descripciones parametros
[ $SIESTA_SETTINGS_DESC_PARAM -nt $SIESTA_SETTINGS_DESC_PARAM_IX ] && gen_ix_desc

# Volcado parametros
echo "				<br>
				<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"

# Recorrer fichero configuracion
while read line; do
	if [ ${#line} -ne 0 ]; then
		if [ ${line:0:1} != "#" ]; then
			# Alternar colores
			if [ "$bgcolor" = "#FFECD9" ]; then
				bgcolor="#FFFFE8"
			else
				bgcolor="#FFECD9"
			fi

			# Obtener datos y valor parametro
			TMP=(`echo $line`)
			NombreParametro=${TMP[0]}
			TipoParametro=${TMP[1]}
			TMP2=`grep ^${NombreParametro} $SIESTA_SETTINGS_FILE | cut -d"=" -f2-`
			ValorParametro=${TMP2# }

			# Nombre parametro
			echo "					<tr bgcolor=\"$bgcolor\">
						<td width=\"25%\" align=\"right\" class=\"txtParam\">
							${NombreParametro}:&nbsp;
						</td>"

			# Tipo de parametro
			echo "						<td width=\"20%\" align=\"left\" class=\"txtParam\">"
			case $TipoParametro in
				key )
					# Parametro key, desplegable
					echo "							<select name=\"${NombreParametro}\" id=\"${NombreParametro}\" class=\"cajaParam\">"
					# Recorrer opciones
					i=2
					TMP2=${TMP[$i]}
					while [ ${#TMP2} -ne 0 ]; do
						echo "								<option value=\"${TMP2}\">${TMP2}</option>"
						i=$(($i+1))
						TMP2=${TMP[$i]}
					done
					echo "							</select>"
					# Valor de la opcion
					echo "							<script type=\"text/javascript\">document.getElementById('${NombreParametro}').value=\"${ValorParametro}\";</script>"
					;;
# 				list ) ;;
				num )
					# Parametro numerico, caja texto
					echo "							<input type=\"num\" name=\"${NombreParametro}\" value=\"${ValorParametro}\" size=\"8\" maxlength=\"32\" class=\"cajaParam\">"
					;;
				str )
					# Parametro string, caja texto
					echo "							<input type=\"text\" name=\"${NombreParametro}\" value=\"${ValorParametro}\" size=\"40\" maxlength=\"128\" class=\"cajaParam\">"
					;;
				*)
					echo "							$TipoParametro"
					;;
			esac
			echo "						</td>"

			# Descripcion parametro
			echo "						<td width=\"1%\">&nbsp;</td>"
			echo "						<td width=\"54%\" align=\"left\" class=\"txtDescParam\">"
			[ $VER_DESCRIPCIONES -ne 0 ] && desc_parametro $NombreParametro
			echo "						</td>
					</tr>"
		fi
	fi
done < $SIESTA_SETTINGS_CONF_FILE

# Botones ayuda y guardar
echo "					<tr>
						<td align=\"center\">
							<br><input type=\"button\" onclick=\"window.open('/cgi-bin/box/verParamSIESTA','paramSIESTA','menubar=no,toolbar=NO,scrollbars=yes,resizable=YES,width=800,height=600');\" value=\"Ayuda parámetros\">
						</td>
						<td colspan=\"2\">&nbsp;</td>
						<td align=\"center\">
							<br><input type=\"button\" onclick=\"guardar();\" value=\"Guardar\">
						</td>
					</tr>
				</table>"

# Final html
html_doc_end
