#!/bin/sh

# Lemmi @ m740.info/forum, 2005-08-22 -> GPL
source ../www-setup
. theme header "Dump der Datei" "Dump der Datei" "Lemmi"

cat << ---EOT---
<h2>$title</h2>
---EOT---

if [[ ! -f "$PATH_INFO" ]]; then
    echo "WARNUNG: Die Datei '$PATH_INFO' existiert nicht."
elif [[ ! -s "$PATH_INFO" ]]; then
    echo "INFO: Die Datei '$PATH_INFO' enthält keine Zeichen."
else
    echo -n '<pre style="background-color:#e8e8ff; padding:.4em">'
    sed 's/&/\&amp;/g;s/</\&lt;/g' "$PATH_INFO"
    echo '</pre>'
fi

cat << ---EOT---
<p>
---EOT---

. theme footer
