#!/bin/sh
# by pepper
# Invocación remota de teclas

tecla=`echo $QUERY_STRING | cut -d"-" -f1`
echo "sim 0 00 $tecla wer_server" > /dev/tcp/localhost/8765

echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<M750><RESULT>OK</RESULT></M750>"
