#!/bin/sh

# El hack se activa desde Mis Grabaciones.
/var/media/USB-HDD/bin/txt2osd -x -1 -y -1 -d 2000 -b 0x7F000000 -s 30 "Desactivando TimeShift"
sleep 1
/data/scripts/irsim.sh TV
sleep 1
/data/scripts/irsim.sh MENU
sleep 4
/data/scripts/irsim.sh CURSOR_UP
usleep 500000
/data/scripts/irsim.sh CURSOR_UP
usleep 500000
/data/scripts/irsim.sh OK
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh OK
usleep 500000
/data/scripts/irsim.sh CURSOR_UP
usleep 500000
/data/scripts/irsim.sh OK
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh CURSOR_DOWN
usleep 500000
/data/scripts/irsim.sh OK
usleep 500000
/data/scripts/irsim.sh TV

echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<M750><RESULT>OK</RESULT></M750>"
