#!/bin/sh
# by pepper
# Invocación remota de teclas

texto=`echo $QUERY_STRING | cut -d"-" -f1`
size=`echo $QUERY_STRING | cut -d"-" -f2`
secs=`echo $QUERY_STRING | cut -d"-" -f3`
/usr/bin/txt2osd -x -1 -y -1 -s $size -b 0x9F000000 -f 0xFFFFFFFF -d ${secs}000 "`echo $texto | sed -e 's/%20/ /g'`"

echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<M750><RESULT>OK</RESULT></M750>"
