#!/bin/bash
# jotabe, (c) Grupo SIESTA, 20-03-2008
#
# Guarda la configuración de LCK

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
LCK_SETTINGS_FILE=/var/etc/LCK.cfg
LCK_SETTINGS_FILE_TMP=${LCK_SETTINGS_FILE}.temp
FLAG_CAMBIOS=${LCK_SETTINGS_FILE}-$$.flag

# Procesar parametros get/post
eval "`proccgi $*`"

# Recorrer fichero
rm -f ${FLAG_CAMBIOS}
awk '{print $0}' $LCK_SETTINGS_FILE | while read line; do
	if [ ${#line} -ne 0 ]; then
		if [ ${line:0:1} != "#" ]; then
			# Obtener nombre y valor parametro actual
			TMP=(`echo $line`)
			NombreParametro=${TMP[0]}
			ValorParametro0=${TMP[1]}
			# Obtener nuevo valor de parametro
			TMP='$'FORM_PAR_${NombreParametro}
			eval "ValorParametro=$TMP"
			# Comprobar cambio de valor
			if [ "Z$ValorParametro" != "Z$ValorParametro0" ]; then
				# Sustituir valor
				line="$NombreParametro	$ValorParametro"
				# Marca cambios
				touch ${FLAG_CAMBIOS}
			fi
		fi
	fi
	# Linea modificada
	echo "$line"
done > $LCK_SETTINGS_FILE_TMP

# Sustituir fichero configuracion
if [ -f ${FLAG_CAMBIOS} ]; then
	rm -f ${FLAG_CAMBIOS}
	mv -f $LCK_SETTINGS_FILE_TMP $LCK_SETTINGS_FILE
	flash_archive write $LCK_SETTINGS_FILE >> /var/log/flash_archive.log 2>&1
fi

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/box/configLCK\"
	</script>
</head>
</html>"
