#!/bin/bash
# jotabe, (c) Grupo SIESTA, 03-12-2007
#
# Guarda la configuración de LCK

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
LCK_SETTINGS_FILE=/var/etc/LCK.cfg
LCK_SETTINGS_FILE_TMP=${LCK_SETTINGS_FILE}.temp

# Procesar parametros get/post
eval "`proccgi $*`"

# Recorrer fichero
sed_script=""
while read line; do
	if [ ${#line} -ne 0 ]; then
		if [ ${line:0:1} != "#" ]; then
			# Obtener nombre y valor parametro actual
			TMP=(`echo $line`)
			NombreParametro=${TMP[0]}
			ValorParametro0=${TMP[1]}
			# Obtener nuevo valor de parametro
			TMP='$'FORM_PAR_${NombreParametro}
			eval "ValorParametro=$TMP"
			if [ "Z$ValorParametro" != "Z$ValorParametro0" ]; then
				# Generar script de sustitucion
				[ ${#sed_script} -ne 0 ] && sed_script="${sed_script};"
				sed_script="${sed_script}s/$line/$NombreParametro $ValorParametro/g"
			fi
		fi
	fi
done < $LCK_SETTINGS_FILE

# Sustituir valores parametros y actualizar configuracion
if [ ${#sed_script} -ne 0 ]; then
	sed -e "$sed_script" $LCK_SETTINGS_FILE > $LCK_SETTINGS_FILE_TMP
	mv -f $LCK_SETTINGS_FILE_TMP $LCK_SETTINGS_FILE
fi

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/box/configLCK\"
	</script>
</head>
</html>"
