#!/bin/sh

function print_top()
{
	cat <<- ---EOT---
        <html>
        <title>M750T - Ver LiveTV</title>
        <link href="/sincro/img/m740.ico" rel="shortcut icon"></link>
        <link href="/sincro/css/estilos.css" rel="stylesheet" type="text/css"></link>
        <script language="JavaScript" src="/sincro/js/ajax.js"></script>
        <script language="JavaScript" src="/sincro/js/navigator.js"></script>
        <script language="JavaScript" src="/sincro/js/controlenviar.js"></script>
        <script>
        function init() {
            index=document.location.href.indexOf("://");
            host=document.location.href.substring(index+3);
            index=host.indexOf("/");
            host=host.substring(0, index);
            document.forms[0].host.value=host;
        }
        function startStream() {
            eval("verCanal("+document.forms[0].canal.value+")");
        }
        function verCanal(frq, p1, p2, p3) {
            f=document.forms[0];
            if (f.ip.value.length == 0) {
                alert("Debes indicar la IP de tu PC local");
                f.ip.focus();
                return;
            }
            f.freq.value=frq;
            f.p1.value=p1;
            f.p2.value=p2;
            f.p3.value=p3;
            f.action="/cgi-bin/box/startdvbstream";
            if (is_ie)
              mostrarMensajeProceso();
            makeRequest(f.action + "?" + getFormParameters(f), "mostrarXMLRespuesta");
        }
        function download() {
            f=document.forms[0];
            f.action="/cgi-bin/box/tvLive";
            document.forms[0].submit();
        }
        function reboot() {
          if (confirm("¿Confirma el reboot del Gigaset?")) {
            makeRequest("/cgi-bin/box/reboot?" + new Date().getTime(), "noReply");
            alert("Se ha mandado la petición de Reboot.\nEn unos segundos el sistema se reiniciará");
          }
        }
        function noReply(xmldoc) {}
        function mostrarXMLRespuesta(xmldoc) {
          if (is_ie)
            eliminarMensajeProceso();
          result = xmldoc.getElementsByTagName("RESULT");
          if (result[0].firstChild.data == "1")
            alert("Servidor DVBStream arrancado correctamente");
          else
            alert("Se ha producido un error arrancando el servidor DVBStream.\nRevisa los datos del path y vuelve a probar.");
        }
        </script>
        <body bgcolor="#FFFFFF" onload="init();">
        <form name="formulario" action="/cgi-bin/box/tvLive" method="get">
        <div align="center"><p><font class="titPag">M750T EPG</font></p></div>
        <div align="center"><font class="subTitPag">Ver LiveTV</font></div>
        <p>
            <div align="center" class="txtNormal"><a href="javascript:history.back()">Atrás</a> | <a href="/cgi-bin/sincro/pgmactualXML">Inicio</a> | 
            <a href="/cgi-bin/crid/timerXML">Grabaciones Pendientes</a> | <a href="/cgi-bin/crid/videoXML">Grabaciones Realizadas</a> | 
            <a href="/index.html">Salir</a><br/><br/><a href="/osd/osd2tcp.html">Control OSD</a></div>
        </p>
        <table width="98%" border="0" cellspacing="0" cellpadding="0" align="center">
        <tr>
        	<td class="txtNormal">Host: </td>
        	<td class="txtNormal"><input type="text" name="host" size="50" maxlength="100" class="cajaplana"></td>
        </tr>
        <tr>
        	<td class="txtNormal">Puerto:</td>
        	<td class="txtNormal"><input type="text" name="port" value="1234" size="5" maxlength="5" class="cajaplana"></td>
        </tr>
        <tr>
        	<td class="txtNormal">IP del PC donde verás la TV: </td>
        	<td class="txtNormal"><input type="text" name="ip" size="17" maxlength="16" class="cajaplana"></td>
        </tr>
        <tr>
        	<td class="txtNormal">Path de dvbstream en el Gigaset:</td>
        	<td class="txtNormal"><input type="text" name="dvbstream" value="/var/media/USB-HDD/bin/dvbstream" size="70" maxlength="200" class="cajaplana"></td>
        </tr>
        <tr>
        	<td class="txtNormal">Path de MPlayer en el PC local:</td>
        	<td class="txtNormal"><input type="text" name="mplayer" value="C:\Archivos de programa\mplayer\mplayer.exe" size="70" maxlength="200" class="cajaplana"></td>
        </tr>
        <tr>
        	<td class="txtNormal">Relación de Aspecto:</td>
        	<td class="txtNormal">
        	    <select size="1" name="aspect">
        	        <option value="1.25" selected>4:3</option>
        	        <option value="1.7777">16:9</option>
        	    </select>
        	</td>
        </tr>
        <tr>
        	<td class="txtNormal" height="20" colspan="2">&nbsp;</td>
        </tr>
		---EOT---
}

function print_bottom()
{
	cat <<- ---EOT---
        <tr>
        	<td class="txtInfo" colspan="2">
        	    <br><br>Para poder ver la TV en directo, hay que matar el wavebox y los procesos que permiten ver la TV en la televisión.<br>
        	    Una vez termines de ver la TV en directo en el PC, deberás reiniciar el M750T para que los procesos wavebox vuelvan a ejecutarse.<br><br>
        	    Para realizar el <u>cambio de canal</u>, finaliza MPlayer (Esq / q) y ejecuta de nuevo desde el Paso 2 al Paso 4. El fichero M750_TVLive.cmd es el mismo
        	    para todos los canales.
        	</td>
        </tr>
        <tr>
        	<td class="txtNormal" height="20" colspan="2">&nbsp;</td>
        </tr>
        <tr>
        	<td class="txtNormal" align="center" colspan="2"><input type="button" value="Reiniciar Gigaset" onclick="reboot();"></td>
        </tr>
        </table><br/>
        <p>
            <div align="center" class="txtNormal"><a href="javascript:history.back()">Atrás</a> | <a href="/cgi-bin/sincro/pgmactualXML">Inicio</a> | 
            <a href="/cgi-bin/crid/timerXML">Grabaciones Pendientes</a> | <a href="/cgi-bin/crid/videoXML">Grabaciones Realizadas</a> | 
            <a href="/index.html">Salir</a><br/><br/><a href="/osd/osd2tcp.html">Control OSD</a><br/><br/>
            <a href="/autores.html">Autores</a></div>
        </p>
        <input type="hidden" name="freq" value="">
        <input type="hidden" name="p1" value="">
        <input type="hidden" name="p2" value="">
        <input type="hidden" name="p3" value="">
        </form>
        </body>
        </html>
		---EOT---
}

source ../www-setup
CACHE_FILE=${Cache}/vertvlive.cache

print_top

echo "    <tr>"
echo "        <td class=\"txtNormal\" height=\"20\" colspan=\"2\">"
echo "          <table width=\"100%\" border=\"0\" cellspacing=\"10\" cellpadding=\"0\" align=\"center\">"
echo "          <tr>"
echo "              <td class=\"txtNormal\" valign=\"top\"><font class="titChannel">Paso 1</font> : <br><br>Descarga el fichero de ejecución de Mplayer y guardalo en tu PC local:<br><br><input type=\"button\" value=\"Descargar M750_TVLive.cmd\" onclick=\"download();\" class=\"cajaPlana\"></td>"
echo "              <td class=\"txtNormal\" valign=\"top\"><font class="titChannel">Paso 2</font> : <br><br>Selección del Canal:<br/><select class=\"cajaPlana\" name=\"canal\" size=1>"

if [ ! -f $CACHE_FILE ]; then
    while read line
    do
        channelName=`echo "$line" | cut -b1-25`
        cn=`echo "$line" | cut -b40-41`
        p1=`echo "$line" | cut -b57-61`
        p2=`echo "$line" | cut -b47-50`
        p3=`echo "$line" | cut -b52-55`
        freq=$((770000000+($cn-58)*8000000))
        echo "<option value=\"'$freq', '`printf %d 0x$p1`', '`printf %d 0x$p2`', '`printf %d 0x$p3`'\">$channelName</option>" >> $CACHE_FILE
    done < /var/etc/services.txt
fi
cat < $CACHE_FILE

echo "              </select></td>"
echo "              <td class=\"txtNormal\" valign=\"top\"><font class="titChannel">Paso 3</font>: <br><br>Matar wavebox y ejecución del <b>dvbstream</b>:<br><br><input type=\"button\" value=\"Iniciar dvbstream\" onclick=\"startStream();\" class=\"cajaPlana\">"
echo "              <td class=\"txtNormal\" valign=\"top\"><font class="titChannel">Paso 4</font>: <br><br>Ejecuta en el PC el fichero <b>M750_TVLive.cmd</b>."
echo "          </tr>"
echo "        </table></td>"
echo "    </tr>"

print_bottom
