#!/bin/bash
# by pepper, 10/05/2007
# Script para la visualización de la TV en directo (necesita matar el wavebox)

function print_OK()
{
    echo Content-type: text/xml
    echo ""
    echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
    echo "<M750><RESULT>1</RESULT></M750>"
}

function print_ERROR()
{
    echo Content-type: text/xml
    echo ""
    echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
    echo "<M750><RESULT>0</RESULT></M750>"
}

host=`echo $QUERY_STRING | cut -d"&" -f1 | cut -d"=" -f2`
port=`echo $QUERY_STRING | cut -d"&" -f2 | cut -d"=" -f2`
localPC=`echo $QUERY_STRING | cut -d"&" -f3 | cut -d"=" -f2`
dvbstream=`echo $QUERY_STRING | cut -d"&" -f4 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%2F/\//g' | sed -e 's/+/ /g'`
mplayer=`echo $QUERY_STRING | cut -d"&" -f5 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/+/ /g'`
aspect=`echo $QUERY_STRING | cut -d"&" -f6 | cut -d"=" -f2`
freq=`echo $QUERY_STRING | cut -d"&" -f8 | cut -d"=" -f2`
p1=`echo $QUERY_STRING | cut -d"&" -f9 | cut -d"=" -f2`
p2=`echo $QUERY_STRING | cut -d"&" -f10 | cut -d"=" -f2`
p3=`echo $QUERY_STRING | cut -d"&" -f11 | cut -d"=" -f2`

pkill -9 dvbstream;pkill -9 inout_wdg
sleep 1
pkill -9 play_backend; pkill -9 record_backend; pkill -9 wavebox; pkill -9 ADSL
sleep 1

isok=`ps -ef | grep dvbstream | wc -l`
if [ $isok -gt 0 ]; then
    echo "ERROR: dvbstream esta todavia en ejecucion." >> /tmp/tvlive.log
    print_ERROR
else
    echo "$dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3" >> /tmp/tvlive.log

    # Iniciamos el servidor de streaming
    if [ -f $dvbstream ]; then
        $dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3 &
        isok=`ps -ef | grep dvbstream | wc -l`
        if [ $isok -eq 1 ]; then
            print_OK
        else
            echo "ERROR: Se ha producido algun error arrancando el servidor dvbstream" >> /tmp/tvlive.log
            print_ERROR
        fi
    else
        echo "ERROR: dvbstream no se encuentra en el path" >> /tmp/tvlive.log
        print_ERROR
    fi
fi
