#!/bin/bash
# pepper, (c) Grupo SIESTA, 10-05-2007
#
# Script para la visualización de la TV en directo (necesita matar el wavebox)

# Configurar entorno
source ../fweb.shi
host=`echo $QUERY_STRING | cut -d"&" -f1 | cut -d"=" -f2`
port=`echo $QUERY_STRING | cut -d"&" -f2 | cut -d"=" -f2`
localPC=`echo $QUERY_STRING | cut -d"&" -f3 | cut -d"=" -f2`
dvbstream=`echo $QUERY_STRING | cut -d"&" -f4 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%2F/\//g' | sed -e 's/+/ /g'`
mplayer=`echo $QUERY_STRING | cut -d"&" -f5 | cut -d"=" -f2 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/+/ /g'`
aspect=`echo $QUERY_STRING | cut -d"&" -f6 | cut -d"=" -f2`
freq=`echo $QUERY_STRING | cut -d"&" -f7 | cut -d"=" -f2`
p1=`echo $QUERY_STRING | cut -d"&" -f8 | cut -d"=" -f2`
p2=`echo $QUERY_STRING | cut -d"&" -f9 | cut -d"=" -f2`
p3=`echo $QUERY_STRING | cut -d"&" -f10 | cut -d"=" -f2`

# Detener procesos wavebox
pkill -9 inout_wdg
sleep 1
pkill -9 wavebox
pkill -9 play_backend
pkill -9 record_backend
sleep 1

# Iniciamos el servidor de streaming
if [ -f $dvbstream ]; then
	# Ejecutar dvbstream
	echo "$dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3 &" >> /tmp/tvlive.log
	$dvbstream -c 0 -f $freq -net $localPC:$port 0 $p1 $p2 $p3 &

	# Resultado OK
	enviar_xml_ok
else
	echo "ERROR: dvbstream no se encuentra en el path" >> /tmp/tvlive.log

	# Resultado NO OK
	enviar_xml_err
fi
