#!/bin/bash
# (c) Grupo SIESTA, 07-12-2007
#
# Ver TV en directo mediante ficheros de timeshift

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
path_mplayer="C:\\\\Archivos de programa\\\\mplayer\\\\mplayer.exe"
[ -f ${SERVER_ROOT}/cfg/.path_mplayer.txt ] && path_mplayer=`sed -e 's/\\\\/\\\\\\\\/g' ${SERVER_ROOT}/cfg/.path_mplayer.txt`
path_temp="C:\\\\Temp"
[ -f ${SERVER_ROOT}/cfg/.path_temp.txt ] && path_temp=`sed -e 's/\\\\/\\\\\\\\/g' ${SERVER_ROOT}/cfg/.path_temp.txt`

# Enviar documento html
http_header
cat ../../html/verTvTS.inc | sed "s/##MPLAYER##/${path_mplayer}/g;s/##TEMP##/${path_temp}/g"
cat ../../html/mplayer.inc
html_doc_end
