#!/bin/bash
# pepper, (c) Grupo SIESTA, 25-07-2007
#
# Volcado fichero START_RECORDER_LOG

# Configurar entorno
source ../www-setup.shi
logfile=/data/START_RECORDER_LOG

# Volcado fichero
cat $logfile \
| sed -e 's/startRecorder was called/<hr width="100%" size="2"><b>&<\/b>\n/g' \
| sed -e 's/Title:\|SeriesID:/<font color="red">&<\/font>/g' \
| sed -e 's/Start:\|End:/<font color="blue">&<\/font>/g'
