#!/bin/sh

#--------------------------------------------------

function html_begin()
{
    cat <<- ---EOT---
	Content-Type: text/html; charset=iso-8859-1
	Expires: `date -R`

	<html>
	<head>
	 <meta http-equiv="expires" content="1">
	 <meta name="author" content="Lemmi @ m740.info/forum">
	 <title>$1</title>
	 <link href="/images/m740.ico" rel="shortcut icon">
	 <style type="text/css">
	  body,img,p { margin 0; padding 0; }

	  h2
	  {
	    color:		#000060;
	    font-family:	Arial,Helvetica,san-serif;
	    font-size:		140%;
	    font-style:		normal;
	    font-weight:	bold;
	    font-variant:	normal;
	    text-align:		left;
	    text-decoration:	none;
	    margin-top:		1.5em;
	    margin-bottom:	0.2em;
	    padding:		0 0 0 0;
	  }

	  p  { margin-top: 1.0ex; }

	  ul
	  {
	    margin: 0;
	    padding: 0 0 0 30px;
	  }

	  li
	  {
	    margin-left: 0.2em;
	    margin-top: 0.5em;
	    text-indent: 0.2em;
	  }
	</style>
	</head>
	<body>
	<h1>$1</h1>
	---EOT---
}

#--------------------------------------------------

function html_end()
{
    cat <<- ---EOT---
	<p><hr><p>
	<a href="/">Zurück zur Startseite</a>
	<p><hr><p>
	<a href="http://www.m740.de/forum/member.php?userid=17">Lemmi</a>,
	<a href="http://de.wikipedia.org/wiki/26._August">2005-08-26</a>,
	<a href="http://www.gnu.org/licenses/gpl.html">GPL</a>
	</body>
	</html>
	---EOT---
}

#--------------------------------------------------

function try_upload()
{
    echo "<div style=\"background-color:#e8e8ff; padding:.4em\"><ul>"

    temp=/var/tmp/save-timer.upload

    echo "<li>Daten speichern</li>"
    head -c 10000 >$temp
    echo "<li>Datei ist ca. `ls -s $temp|awk '{print $1}'` KiB groß.</li>"
    
    echo "</ul></div>"
    true;
}

#--------------------------------------------------

function print_info()
{
    name="timer-`date +%F-%H%M%S`"

    cat <<- ---EOT---

	<h2>Timer Daten auf die Box hochladen</h2>

	<div style="margin: 10px 0 0 0; border:2px solid #800000;
	    padding: .2em 1em; background-color:#ffe0e0;">
	<b>Der Upload läuft noch ins Leere &rarr; es passiert nichts.</b>
	</div>

	<p>
	Die Daten werden geladen und einer Plausibilitätzkontrolle unterzogen.
	<p>
	Sollte alles Ok sein, dann wird
	<ul>
	<li>die <a href="http://www.m740.de/wiki/index.php/wavebox">wavebox</a> angehalten,
	<li>die Timer-Daten geschrieben und
	<li>ein reboot ausgelöst.
	</ul>
	<p>

	<div>
	  <form ENCTYPE="multipart/form-data" method="post" action="$SCRIPT_NAME?file=">
	    <input type="file" size="48" name="file">
	    <input type="submit" name="submit" value="Timer einspielen!">
	  </form>
	</div>

	<h2>Timer Daten sichern</h2>

	Es werden zwei Archiv-Formate unterstützt:
	<ul>
	<li><a href="$SCRIPT_NAME/$name.tar.gz?gzip"><tt>timer-&lt;date+time>.tar.gz</tt><a> (gzip)
	<li><a href="$SCRIPT_NAME/$name.tar.bz2?bzip2"><tt>timer-&lt;date+time>.tar.bz2</tt><a> (bzip2)
	</ul>

	---EOT---
}

#--------------------------------------------------

function send_timer()
{
    fname="timer-`date +%F-%H%M%S`$2"
    cat <<- ---EOT---
	Content-Type: application/x-$1
	Content-Disposition: attachment; filename="$fname"
	Expires: `date -R`

	---EOT---
    tar cf - -C /data .timer RA_FILE SM_FILE RECORDER_LOG | $1
}

#--------------------------------------------------

if echo "$QUERY_STRING" | grep -q '^file='; then

    html_begin "Save-Timer: Upload"
    if ! try_upload; then
	echo "<h1>Neuer Versuch</h1>"
	print_info
    fi
    html_end

elif [[ "$QUERY_STRING" == "gzip" ]]; then

    send_timer gzip .tar.gz

elif [[ "$QUERY_STRING" == "bzip2" ]]; then

    send_timer bzip2 .tar.bz2

else

    html_begin "Save-Timer"
    print_info
    html_end

fi

