#!/bin/bash
# RECORD [CID] [SERIE{0,1}]  CID=ID PROGRAMA + ID CANAL
# TIMER [SERVICEID] [ini] [fin] [did] [nid] [txt]
#pid: Cadena numérica de 12 dígitos formado por un identificador de programa (cifra de 7 dígitos) y un cid (ver abajo) 
#sid: 0 (serie no), 1 (serie si) 
#cid: Cadena numérica de 5 dígitos que identifica una emisora (aparece en services.txt) (*) 
#ini: Hora posix de inicio del programa (segundos desde 1-1-1970 00:00UTC) 
#fin: Hora posix de fin del programa 
#did: Dias en los que se graba la serie. Obtenidos a partir de byte, donde bit7 es domingo, bit6 sábado... bit1 lunes y bit0 vale 1 si es serie. 
#nid: Número de veces que se grabará el programa, no evaluado si no se graba serie. 
#txt: Nombre del programa en ASCII 
#ans: 0 (no aceptado), 1 (aceptado)
# CANCEL [CID]

wcpre=`cat /data/RA_FILE | wc -l`
echo "CANCEL $QUERY_STRING" > /dev/tcp/localhost/2010
sleep 2
wcpost=`cat /data/RA_FILE | wc -l`
if [ $wcpre -gt $wcpost ]; then
   echo "1"
else
   echo "0"
fi
