#!/bin/bash 
# by pepper 27/06/2007
# Retorna la sincroguia completa en formato de parrilla

source ../www-setup
SORT_CHANNELS=$Cache/sort_channels.txt
PARRILLA_CHANNELS=$Cache/parrilla_channels.txt

# Generamos el fichero sort_channels.txt con la misma ordenación del gigaset
[ ! -f $SORT_CHANNELS ] && ./sortChannels

if [ -f $SORT_CHANNELS ]; then
	ListaCanales=`cat $SORT_CHANNELS`
else
	ListaCanales=$EPG_PATH/*.db
fi

# Comprobamos si el directorio de imagenes de la sincro de la carpeta de grabaciones esta accesible
if [ -d $SERVER_ROOT/sincro/epg/ ]; then
    DIR_IMG_SINCRO_ACCESIBLE=si
else
    DIR_IMG_SINCRO_ACCESIBLE=no
fi

if [ -f $PARRILLA_CHANNELS ]; then
    numCanales=`cat $PARRILLA_CHANNELS | wc -l`
else
    numCanales=`cat $SORT_CHANNELS | wc -l`
fi

echo Content-type: text/html
echo ""

cat <<-EOF
<html>
  <title>M750T - Sincroguía</title>
  <meta http-equiv="refresh" content="600">
  <link href="/sincro/img/m740.ico" rel="shortcut icon"></link>
  <link href="/sincro/css/estilos.css" rel="stylesheet" type="text/css"></link>
  <script language="JavaScript" src="/sincro/js/ajax.js"></script>
  <script language="JavaScript" src="/sincro/js/navigator.js"></script>
  <script language="JavaScript" src="/sincro/js/controlenviar.js"></script>
  <script language="JavaScript" src="/sincro/js/fechasOp.js"></script>
  <script language="JavaScript" src="/sincro/js/botones.js"></script>
  <script>
  utcParrilla=`cat $Cache/horaUTCinicial.txt`;
  utcAhora=`date +%s`;
  porcentHeight=4;
  heightNow=((utcAhora-utcParrilla)/100)*porcentHeight;
  function record(id, serie, titulo) {
    enserie="";
    if (serie == 1)
        enserie="en serie ";
    if (confirm("¿Está seguro de querer grabar " + enserie + "el programa " + titulo + "?")) {
      mostrarMensajeProceso();
      makeRequest("/cgi-bin/sincro/recordXML?" + parseInt(id, 16) + "-" + serie + "-" + new Date().getTime(), "mostrarXMLRespuesta");
    }
  }
  function mostrarXMLRespuesta(xmldoc) {
    eliminarMensajeProceso();
    result = xmldoc.getElementsByTagName("RESULT");
    if (result[0].firstChild.data == "1")
      alert("Programación aceptada por el M750");
    else
      alert("Programación NO aceptada por el M750");
  }
  function detail(pid, img, long, channel, utc) {
    document.location.href="/cgi-bin/sincro/pgmdetailXML?"+parseInt(pid, 16)+"-"+img+"-"+long+"-"+channel+"-"+utc;
  }
  function buscar() {
    mostrarMensajeProceso();
    document.location.href="/cgi-bin/sincro/searchXML?" + document.forms['formulario'].querystr.value;
  }
  function buscarFH() {
    f=document.forms['formulario'];
    mostrarMensajeProceso();
    document.location.href="/cgi-bin/sincro/searchXML?" + f.fecha.value + " " + f.hora.value;
  }
  function cambioCanal(num) {
    makeRequest("/cgi-bin/box/cambioCanal?" + num + "-" + new Date().getTime(), "noReply");
  }
  function noReply() {
  }
  function initFechas(fecha) {
    f=document.forms[0];
    var d = new Date();    
    dia=(""+d.getDate()).length == 1 ? "0" + d.getDate() : d.getDate();
    mes=(""+(d.getMonth()+1)).length == 1 ? "0" + (d.getMonth()+1) : (d.getMonth()+1);
    fullYear=""+d.getFullYear();
    year=fullYear.substring(2);
    f.fecha.length=7;
    f.fecha.options[0].text=dia+"."+mes+"."+fullYear;
    f.fecha.options[0].value=dia+"."+mes+"."+year;
    for(i=1; i < 7; ++i) {
      f.fecha.options[i].text=incDate(f.fecha.options[i-1].text);
      f.fecha.options[i].value=f.fecha.options[i].text.substring(0,6)+f.fecha.options[i].text.substring(8);
    }
  }
  function crearHrNow() {
    hrrednow = document.createElement("div");
    hrrednow.setAttribute("id","hrnow");
    hrrednow.style.position = 'absolute';
    hrrednow.style.width  = '$((numCanales*155))';
    hrrednow.style.zIndex = '99';
    if (is_ie) {
        hrrednow.style.left = "14 px";
        hrrednow.style.top = (heightNow + 295) + " px";
    }
    else {
        hrrednow.style.left = "14";
        hrrednow.style.top = (heightNow + 278);
    }
    hrrednow.innerHTML= '<A NAME="ahora"><hr width="100%" size="3" color="#FF0000"></A>';
    document.body.appendChild(hrrednow);
  }
  </script>
  <body bgcolor="#FFFFFF" onload="initFechas(); crearHrNow();">
    <form name="formulario">
    <div align="center"><p><font class="titPag">M750T EPG</font></p></div>
    <div align="center"><a href="http://www.inout.tv/SincroGuia"><img src="/sincro/img/sincro.gif" border="0"/></a><font class="subTitPag">proporcionada por InOut TV</font></div>
    <script language="JavaScript">barra_botones();</script>
    <table width="98%" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr>
      <td class="txtNormal">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="txtNormal">
        <tr>
        	<td align="left" width="150"><a href="#ahora" title="Ir al programa actual">Ir al programa actual</a></td>
        	<td align="center"><a href="/cgi-bin/sincro/configParrilla" title="Configurar Parrilla">Configurar Parrilla</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        </tr>
        </table>
        <div align="right">Buscar Programa: <input class="cajaplana" name="querystr" type="text" size="20" maxsize="50" value="" /> <input class="txtNormal" type="button" value="Buscar" onclick="buscar()" /><br/>
        Búsqueda Horaria: 
        Fecha: <select size="1" name="fecha"><option value="">Procesando...</option></select>
        Hora: <select size="1" name="hora">
                <option value="00:">0</option>
                <option value="01:">1</option>
                <option value="02:">2</option>
                <option value="03:">3</option>
                <option value="04:">4</option>
                <option value="05:">5</option>
                <option value="06:">6</option>
                <option value="07:">7</option>
                <option value="08:">8</option>
                <option value="09:">9</option>
                <option value="10:">10</option>
                <option value="11:">11</option>
                <option value="12:">12</option>
                <option value="13:">13</option>
                <option value="14:">14</option>
                <option value="15:">15</option>
                <option value="16:">16</option>
                <option value="17:">17</option>
                <option value="18:">18</option>
                <option value="19:">19</option>
                <option value="20:">20</option>
                <option value="21:">21</option>
                <option value="22:">22</option>
                <option value="23:">23</option>
            </select>
            <input class="txtNormal" type="button" value="Buscar" onclick="buscarFH()" /></div>
      </td>
    </tr>
    </table>
    <br>
    <table border="0" cellspacing="1" cellpadding="0" align="left">
    <tr>
EOF

bgcolor="#FFFFE8"
for Sincrofile in $ListaCanales ; do
    CHANNEL_ID=`echo $Sincrofile | cut -d"_" -f2 | cut -d"." -f1`
    CACHE_FILE=${Cache}/sincrochannelXML.cache.$CHANNEL_ID
    CACHE_HTML=${Cache}/sincrochannelXML.cache.$CHANNEL_ID.html
    if [ -f ${CACHE_FILE} ]; then
        chName=`head -1 ${CACHE_FILE} | cut -d"\"" -f6`
    else
        chName=$CHANNEL_ID
    fi
    show=1
    if [ -f $PARRILLA_CHANNELS ]; then
        isSelected=`grep "Z$chName" $PARRILLA_CHANNELS | wc -l`
        if [ $isSelected -eq 0 ]; then
            show=0
        fi
    fi
    if [ $show -eq 1 ]; then
        if [ "$bgcolor" = "#FFECD9" ]; then
            bgcolor="#FFFFE8"
        else
            bgcolor="#FFECD9"
        fi
        echo "          <td valign=\"top\" align=\"center\" width=\"140\" class=\"titChannel\" class=\"borderFila\" nowrap><a href=\"/cgi-bin/sincro/sincrochannelXML?$CHANNEL_ID-0\">$chName</a>"
        echo "<br><font class=\"txtMuyPeq\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>"
        echo "              <table border=\"0\" bgcolor=\"$bgcolor\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"borderTabla\">"
        if [ -f ${CACHE_HTML} ]; then
            cat < ${CACHE_HTML}
        else
            echo "<tr><td class=\"borderFila txtNormal\">La caché de este canal no está generada. Espere a que se genere la caché o fuerce la actualización desde la pantalla de <a href=\"/cgi-bin/box/estado\">Estado</a>.</td></tr>"
        fi
        echo "          </table>"
        echo "      </td>"
    fi
done
cat <<-EOF
      </tr>
   <tr>
       <td colspan="8">
       <script language="JavaScript">barra_botones();</script>
       </td>
   </tr>
      </table>
</form>
</body>
</html>
EOF