#!/bin/bash
# (c) Grupo SIESTA, 11-07-2007
#
# Retorna el XML con el detalle de un programa

# Ejecutamos el script con baja prioridad
renice 20 $$ > /dev/null

# Obtener parametros
pid=`echo $QUERY_STRING | cut -d"-" -f1`
img=`echo $QUERY_STRING | cut -d"-" -f2`
long=`echo $QUERY_STRING | cut -d"-" -f3`
channel=`echo $QUERY_STRING | cut -d"-" -f4`
utc=`echo $QUERY_STRING | cut -d"-" -f5`
#pid=`echo $1 | cut -d"-" -f1`
#img=`echo $1 | cut -d"-" -f2`
#long=`echo $1 | cut -d"-" -f3`
#channel=`echo $1 | cut -d"-" -f4`

# Configurar entorno
DiaSemana=([1]="Lun" [2]="Mar" [3]="Mie" [4]="Jue" [5]="Vie" [6]="Sab" [7]="Dom")
source ../www-setup

# Comprobar imagen
if [ "Z$img" != "Z" ]; then
	# Comprobar si existe la imagen
	if [ -f ${SERVER_ROOT}/sincro/epg/$img ]; then
		urlimg="/sincro/epg/$img"
	else
		# No existe imagen, comprobar si obtenerla de internet
		if [ "Z$OBTENER_IMG_INET" = "Zsi" ]; then
			urlimg="http://www.inout.tv/fotos/$img"
		else
			urlimg="/sincro/img/epg_long_img.png"
		fi
	fi
else
	urlimg="/sincro/img/epg_long_img.png"
fi

# Extraer fichero descripciones largas
EPG_LONG_FILE=$EPG_PATH/EPGLong_$channel.txt.bz2
EPG_LONG_FILE_UNZIP=$Cache/EPGLong_$channel.txt
[ $EPG_LONG_FILE -nt $EPG_LONG_FILE_UNZIP ] && bzcat $EPG_LONG_FILE > $EPG_LONG_FILE_UNZIP

# Extrar texto
text=`www-tools get-epg-long $EPG_LONG_FILE_UNZIP $long`

# Comprobar grabacion pendiente
inRA=`grep $pid /data/RA_FILE | wc -l`
if [ $inRA -gt 0 ]; then
	pendiente=1
else
	pendiente=0
fi

# Eliminar fichero descripciones largas
[ "Z$CACHE_EPG_LONG" = "Zno" ] && rm -f $EPG_LONG_FILE_UNZIP

# Obtener fecha
#dateFormat=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M - %a\" , $utc) }"`
ds=`awk "BEGIN {print strftime( \"%u\" , $utc) }"`
dateFormat=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $utc) }"`
dateFormat="$dateFormat, ${DiaSemana[ds]}"

# Generar resultado XML
cat <<- ---EOT---
Content-type: text/xml

<?xml version="1.0" encoding="ISO-8859-1" ?>
<?xml-stylesheet type="text/xsl" href="/sincro/sincrodetail.xsl"?>
<M750>
	<PGMDETAIL>
		<TEXT>$text</TEXT>
		<IMG>$urlimg</IMG>
		<LONG>$long</LONG>
		<PIDCID>$pid</PIDCID>
		<CHANNEL_ID>$channel</CHANNEL_ID>
		<DATE>$dateFormat</DATE>
		<PROGRAMMED>$pendiente</PROGRAMMED>
	</PGMDETAIL>
</M750>
---EOT---
