#!/bin/bash
# (c) Grupo SIESTA, 27-07-2007
#
# Retorna el XML con el detalle de un programa
# pgmdetail?pid-img-long-chID-utc

# Ejecutamos el script con baja prioridad
renice 20 $$ > /dev/null

# Obtener parametros
pid=`echo $QUERY_STRING | cut -d"-" -f1`
img=`echo $QUERY_STRING | cut -d"-" -f2`
long=`echo $QUERY_STRING | cut -d"-" -f3`
chID=`echo $QUERY_STRING | cut -d"-" -f4`
utc=`echo $QUERY_STRING | cut -d"-" -f5`

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
DiaSemana=([1]="Lun" [2]="Mar" [3]="Mie" [4]="Jue" [5]="Vie" [6]="Sab" [7]="Dom")

# Comprobar imagen
if [ "Z$img" != "Z" ]; then
	# Comprobar si existe la imagen en carpeta local
	if [ -f ${SERVER_ROOT}/img/epg/$img ]; then
		urlimg="/img/epg/$img"
	else
		# No existe imagen local, comprobar si obtenerla de internet
		if [ "Z$OBTENER_IMG_INET" = "Zsi" ]; then
			urlimg="http://www.inout.tv/fotos/$img"
		else
			urlimg="/img/epg_long_img.png"
		fi
	fi
else
	urlimg="/img/epg_long_img.png"
fi

# Extraer fichero descripciones largas
EPG_LONG_FILE=$EPG_PATH/EPGLong_$chID.txt.bz2
EPG_LONG_FILE_UNZIP=$Cache/EPGLong_$chID.txt
[ $EPG_LONG_FILE -nt $EPG_LONG_FILE_UNZIP ] && bzcat $EPG_LONG_FILE > $EPG_LONG_FILE_UNZIP

# Extrar texto
text=`www-tools get-epg-long $EPG_LONG_FILE_UNZIP $long`

# Comprobar grabacion pendiente
inRA=`grep $pid /data/RA_FILE | wc -l`
if [ $inRA -gt 0 ]; then
	pendiente=1
else
	pendiente=0
fi

# Eliminar fichero descripciones largas
[ "Z$CACHE_EPG_LONG" = "Zno" ] && rm -f $EPG_LONG_FILE_UNZIP

# Obtener fecha
ds=`awk "BEGIN {print strftime( \"%u\" , $utc) }"`
dateFormat=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $utc) }"`
dateFormat="$dateFormat, ${DiaSemana[ds]}"

# Enviar documento xml
xml_doc "/xsl/sincrodetail.xsl"

# Resultado xml
echo "<M750>
	<PGMDETAIL>
		<TEXT>$text</TEXT>
		<IMG>$urlimg</IMG>
		<LONG>$long</LONG>
		<PIDCID>$pid</PIDCID>
		<CHANNEL_ID>$chID</CHANNEL_ID>
		<DATE>$dateFormat</DATE>
		<PROGRAMMED>$pendiente</PROGRAMMED>
	</PGMDETAIL>
</M750>"
