#!/bin/bash 
# by pepper 03/04/2007
# Busca la cadena de texto en los ficheros de caché

# Ejecutamos el script con baja prioridad
renice 20 $$ > /dev/null

if [ $# != 0 ] ; then
	search=$1
else
	search=$QUERY_STRING
fi

source ../www-setup
SEARCH_RESULT=$Cache/search_result.txt

query=`echo $search | sed -e 's/%20/ /g'`
echo "`date` \"$query\"" >> /tmp/search.log
grep -i "$query" $Cache/*.text > $SEARCH_RESULT
fileAnt=""

if [ -d $SERVER_ROOT/sincro/epg/ ]; then
    DIR_IMG_SINCRO_ACCESIBLE=si
else
    DIR_IMG_SINCRO_ACCESIBLE=no
fi

echo Content-type: text/xml
echo ""
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>"
echo "<?xml-stylesheet type=\"text/xsl\" href=\"/sincro/search.xsl\"?>"
echo "<M740><SINCROGUIA miniatures=\"$MOSTRAR_MINI_IMG\" getImgInet=\"$OBTENER_IMG_INET\" localSincroImgAcc=\"$DIR_IMG_SINCRO_ACCESIBLE\">"

while read line
do
    file=`echo $line | cut -d":" -f1`
    channelId=`echo $file | cut -d"." -f3`
    dateIni=`echo $line | cut -d"_" -f1 | cut -d":" -f2`
	pid=`echo $line | cut -d"_" -f2`
	pidcid=`echo $line | cut -d"_" -f3`
	dateFormatIni=`echo $line | cut -d"_" -f4`
	longs=`echo $line | cut -d"_" -f5`
	titulo=`echo $line | cut -d"_" -f6`
	subtitulo=`echo $line | cut -d"_" -f7`
	imagen=`echo $line | cut -d"_" -f8`
	
	if [ "$fileAnt" != "$file" ]; then
	    mapping=`grep ${channelId} /var/etc/eps_mapping.txt | head -1`
        chName=`echo "$mapping" | cut -d":" -f 1`
        lines=`cat /var/etc/services.txt | grep "$chName" | wc -l`
        if [ $lines -eq 0 ]; then
            mapping=`grep ${channelId} /var/etc/eps_mapping.txt | tail -1`
            idsec=`echo "$mapping" | cut -d"," -f 2`
            if [ "$idsec" = "$channelId" ]; then
                chName=`echo "$mapping" | cut -d":" -f 1`
            fi
        fi
        #cid=`cat /var/etc/services.txt | cut -b 87-145 | grep "${channelId} " | cut -b 55-60 | head -1`
        if [ "$fileAnt" != "" ]; then
            echo "</CHANNEL>"
        fi
        echo "<CHANNEL cid=\"\" id=\"${channelId}\" name=\"$chName\">"
	fi
	echo "<PROGRAM id=\"${pid}\" pid=\"${pidcid}\" chid=\"${channelId}\">"
    echo "<TITLE>$titulo</TITLE><SUBTITLE>$subtitulo</SUBTITLE><IMAGE>$imagen</IMAGE><LONG>$longs</LONG>"
    echo "<DATE>$dateFormatIni</DATE><DATE_UTC>$dateIni</DATE_UTC></PROGRAM>"
    fileAnt=$file
done < $SEARCH_RESULT
rm -f $SEARCH_RESULT
if [ "$fileAnt" != "" ]; then
    echo "</CHANNEL>"
fi
echo "</SINCROGUIA></M740>"
