#!/bin/bash
# pepper, (c) grupo SIESTA, 16-08-2007
#
# Script que lanza la comprobacion de HD en background

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Ejecutar generacion cache XML
run-http.sh /bin/checkDisk.sh &

# Resultado OK
enviar_xml_ok
