#!/bin/bash
# pepper, (c) grupo SIESTA, 16-08-2007
#
# Script que lanza la comprobacion de HD en background

# Obtener parametros
partition=`echo $QUERY_STRING | cut -d"&" -f1`
fstype=`echo $QUERY_STRING | cut -d"&" -f2`

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login "xml"

# Ejecutar comprobacion de disco duro
run-http.sh /bin/checkDisk.sh "$partition" "$fstype" &

# Resultado OK
enviar_xml_ok
