#!/bin/bash
# by pepper 16/05/2007
# Script que realiza un apagado total del gigaset

TOTALOFF_FILE=/tmp/.totalOff

function get_modo_video () {
    # Buscar nº de modulos que estan usando el modulo video
    M_V=(`lsmod | grep ^video`)
    if [ ${M_V[2]} = 0 ] ; then
        ModoVideo="Apagado"
    else
        ModoVideo="Encendido"
    fi
}

sleep $1

get_modo_video

rm -f ${TOTALOFF_FILE}
if [ "$ModoVideo" = "Encendido" ]; then
    # Salimos de una posible visualización de grabacion para que quede la marca de "desde donde lo dejé"
    /data/scripts/irsim.sh TV
    sleep 4
    # Apagado rápido
    /data/scripts/irsim.sh POWER
    sleep 15
fi

# Apagado total
/data/scripts/irsim.sh STOP
