#!/bin/bash
# pepper, (c) Grupo SIESTA, 02-05-2007
#
# Script que genera un fichero de comandos con las instrucciones necesarias para
# visualizar el timeshift en el PC local mediante MPlayer

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login

# Procesar parametros get/post
eval "`proccgi $*`"

# Obtener parametros
host=$FORM_host
port=$FORM_port
Cridfile=$FORM_cridfile
user=$FORM_user
pwd=$FORM_pwd
mplayer=$FORM_mplayer
tmpdir=`echo $FORM_temp | sed 's/\\\\$//'`
aspect=$FORM_aspect
# so=$FORM_so

# Por si el host viene con puerto, lo quitamos para el ftp y lo dejamos para el http
ftphost=`echo $host | cut -d":" -f1`

# Opciones de mplayer
mplayerOptions="-cache 4096 -quiet -noaspect -aspect $aspect -autosync 30 -framedrop"

# Obtener carpeta de grabaciones
DIR_MPG=`awk '/DeviceRecordingFolder/ {print $2}' /var/etc/settings.txt`
plsfile=$tmpdir\\mplayer_temp_`date +%s`.pls

# Guardar configuracion
echo "${mplayer}" > ${SERVER_ROOT}/cfg/.path_mplayer.txt
echo "${tmpdir}" > ${SERVER_ROOT}/cfg/.path_temp.txt

# Enviar verts.cmd
echo "Content-type: application/octet-stream"
echo "Content-Disposition: attachment; filename=verts.cmd"
echo ""

# Inicio script, variables de entorno
echo "@ECHO OFF"
echo "ECHO \"Iniciando...\""
echo SET USUARIO="$user"
echo SET PASS="$pwd"
echo SET HOST="$host"
echo SET FTP_HOST="$ftphost"
echo SET FTP_PORT="$port"
echo SET BASE_URL="http://%HOST%"
echo SET TEMP="$tmpdir"
echo SET MPLAYER="$mplayer"
echo SET OPCIONES_MPLAYER="$mplayerOptions"
echo SET CADENA_FTP="ftp://%USUARIO%:%PASS%@%FTP_HOST%:%FTP_PORT%"

# Generacion playlist para mplayer
echo ""
echo "REM Generacion playlist para mplayer"
# ultmpg=`./getmpgts`
ultmpg=`basename \`ls -1 $DIR_MPG/*.mpg | tail -n1\``
i=`echo $ultmpg | cut -d"." -f3`
i=$((i+1-1))
fmpg=`echo $ultmpg | cut -d"." -f1`.fmpg
while [ $i -lt 40 ]; do
	if [ $i -lt 10 ]; then
		echo "ECHO ${fmpg}.00$i.mpg >> $plsfile"
	else
		echo "ECHO ${fmpg}.0$i.mpg >> $plsfile"
	fi
	i=$((i+1))
done

# Generacion script start_mplayer.cmd
echo ""
echo "REM Generacion script start_mplayer.cmd"
echo "ECHO @ECHO OFF > $tmpdir\start_mplayer.cmd"
echo "ECHO ECHO Llenando el buffer de MPlayer con wget. Espera unos segundos .... >> $tmpdir\start_mplayer.cmd"
echo "ECHO sleep 15 >> $tmpdir\start_mplayer.cmd"
echo "ECHO \"%MPLAYER%\" %OPCIONES_MPLAYER% -playlist $plsfile >> $tmpdir\start_mplayer.cmd"
echo "ECHO DEL /f /q $tmpdir\*.mpg >> $tmpdir\start_mplayer.cmd"
echo "ECHO DEL /f /q $tmpdir\*.pls >> $tmpdir\start_mplayer.cmd"
echo "ECHO EXIT >> $tmpdir\start_mplayer.cmd"
echo "REM Lanzamos el reproductor en background, mientras continua la descarga del fichero (wget) en foreground"
echo "START /b $tmpdir\start_mplayer.cmd"

# Bucle
echo ""
echo ":bucle"
echo "REM Obtenemos el fichero del timeshift"
echo "wget -q -O - http://$host/cgi-bin/crid/getmpgts?$DIR_MPG > %TEMP%\ultmpg"
echo "SET /P FICHERO=<%TEMP%\ultmpg"
echo "SET NOMBRE_COMPLETO=%CADENA_FTP%$DIR_MPG/%FICHERO%"
echo "GOTO inicio"

# Recargar
echo ""
echo ":recargar"
echo "REM Damos tiempo para que el gigaset genere fichero mpg antes de continuar descargando"
echo "sleep 8"

# Inicio proceso
echo ""
echo ":inicio"
echo "REM Descarga contínua del fichero de timeshift"
echo "wget --continue --passive-ftp -P $tmpdir %NOMBRE_COMPLETO%"
echo "REM Una vez descargado, comprobamos los tamaños para ver si esta completo ya el mpg"
echo "wget -q -O - http://$host/cgi-bin/crid/getfilesize?$DIR_MPG/%FICHERO% > $tmpdir/filesize.tmp"
echo "REM Por si el mpg no esta completo damos 1 segundo para que el gigaset siga escribiendo y asi los tamaños no cuadren"
echo "sleep 1"
echo "SET /P FILE_SIZE_GIGA=<$tmpdir\filesize.tmp"
echo "REM Calculamos el tamaño del fichero descargado"
echo "wc -c $tmpdir\%FICHERO% | cut -d c -f 1 > $tmpdir\filesize2.tmp"
echo "SET /P FILE_SIZE_PC=<$tmpdir\filesize2.tmp"
echo "REM Comprobamos los tamaños de ambos ficheros"
echo "wget -q -O - http://$host/cgi-bin/crid/checkfilesizes?%FILE_SIZE_GIGA%-%FILE_SIZE_PC% > $tmpdir/checksize.tmp"
echo "SET /P CHECK_SIZE=<$tmpdir\checksize.tmp"
echo "IF \"%CHECK_SIZE%\" == \"NO\" GOTO recargar"
echo "GOTO bucle"
