#!/bin/bash 
# pepper, (c) Grupo SIESTA, 03-04-2007
#
# Busca la cadena de texto en los ficheros de caché

# Ejecutamos el script con baja prioridad
renice 20 $$ > /dev/null

# Obtener parametros
if [ $# != 0 ] ; then
	search=$1
else
	search=$QUERY_STRING
fi

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
LOG=/var/log/search.log
SORT_CHIDS=${Cache}/sort_chIDs.txt
SEARCH_RESULT=${Cache}/search_result.txt

# Log de busqueda actual
query=`echo $search | sed -e 's/%20/ /g'`
echo "`date` \"$query\"" >> $LOG

# Recorrer lista de canales
echo -n "" > $SEARCH_RESULT
if [ -f $SORT_CHIDS ]; then
	for chID in `cat $SORT_CHIDS`; do
		# Buscar en fichero .text
		grep -H -i "$query" ${Cache}/cache.${chID}.text >> $SEARCH_RESULT
	done
fi

# Comprobar directorio de imagenes de sincroguia en carpeta de grabaciones
if [ -d $SERVER_ROOT/img/epg/ ]; then
	DIR_IMG_SINCRO_ACCESIBLE=si
else
	DIR_IMG_SINCRO_ACCESIBLE=no
fi

# Enviar documento xml con resultado busqueda
xml_doc "/xsl/sincro.xsl"
echo "	<M750>
	<SINCROGUIA actual=\"0\" titulo=\"Resultado de búsqueda\" subtitulo=\"Resultado de búsqueda\" miniatures=\"$MOSTRAR_MINI_IMG\" getImgInet=\"$OBTENER_IMG_INET\" localSincroImgAcc=\"$DIR_IMG_SINCRO_ACCESIBLE\">"

# Recorrer resultados
buscarPrograma.awk -v "cache=${Cache}" $SEARCH_RESULT

# Eliminar temporales
rm -f $SEARCH_RESULT

echo "	</SINCROGUIA>
</M750>"
