#!/bin/sh
# by pepper, (c) grupo SIESTA
# Script que realiza la descarga de todas las imagenes de la sincro a la carpeta de grabaciones

function get_modo_video () {
    # Buscar nº de modulos que estan usando el modulo video
    M_V=(`lsmod | grep ^video`)
    if [ ${M_V[2]} = 0 ] ; then
        ModoVideo="OFF"
    else
        ModoVideo="ON"
    fi
}

echo "`date` Iniciando la descarga de imágenes de la sincroguía" > /tmp/getsincroimg.log

# Nos guardamos el estado inicial del giga por si está apagado, apagarlo al final
get_modo_video
echo "`date` El M750 está $ModoVideo, y así lo dejaremos al acabar la descarga" >> /tmp/getsincroimg.log

if [ "$ModoVideo" = "OFF" ]; then
    /data/scripts/irsim.sh POWER
    echo "`date` Encendiendo el gigaset..." >> /tmp/getsincroimg.log
    sleep 10
fi

source ../www-setup

echo "`date` Resolviendo la IP del servidor www.inout.tv" >> /tmp/getsincroimg.log
ipInOut=`ping -c 1 www.inout.tv | head -1 | cut -d"(" -f2 | cut -d")" -f1`
echo "`date` Servidor www.inout.tv, IP=[$ipInOut]" >> /tmp/getsincroimg.log
URL_INOUT=http://$ipInOut/fotos
RecordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`
if [ -d $RecordingFolder/EPG/ ]; then
    echo "`date` Borramos las imagenes antiguas... [rm -f $RecordingFolder/EPG/*.jpg]" >> /tmp/getsincroimg.log
    rm -f $RecordingFolder/EPG/*.jpg
    
    for textfile in $Cache/*.text
    do
        while read line
        do
            img=`echo $line | cut -d"_" -f8`
            if [ "$img" != "" ]; then
                echo "wget -P $RecordingFolder/EPG $URL_INOUT/$img" >> /tmp/getsincroimg.log
                wget -q -P $RecordingFolder/EPG $URL_INOUT/$img >> /tmp/getsincroimg.log 2> /tmp/getsincroimg.err
            fi
        done < $textfile
    done
    
    echo "`date` Finalizada la descarga de imágenes de la sincroguía" >> /tmp/getsincroimg.log
else
    echo "`date` El directorio de las imagenes no está disponible... Abortamos el proceso" >> /tmp/getsincroimg.log
fi
if [ "$ModoVideo" = "OFF" ]; then
    /data/scripts/irsim.sh POWER
    echo "`date` Apagando el gigaset..." >> /tmp/getsincroimg.log
fi
