#!/bin/bash
# by pepper
# Script que programa una grabacion y retorna el resultado en XML
echo "`date` Peticion de grabacion entrante: $QUERY_STRING" >> /tmp/record.log

echo Content-type: text/xml
echo ""
pid=`echo $QUERY_STRING | cut -d"-" -f1`
serie=`echo $QUERY_STRING | cut -d"-" -f2`
wcpre=`cat /data/RA_FILE | wc -l`
echo "RECORD $pid $serie" > /dev/tcp/localhost/2010
sleep 4
wcpost=`cat /data/RA_FILE | wc -l`

echo "<M750>"
if [ $wcpre -lt $wcpost ]; then
   echo "<RESULT>1</RESULT>"
   echo "`date` Resultado: OK" >> /tmp/record.log
else
   echo "<RESULT>0</RESULT>"
   echo "`date` Resultado: NOK" >> /tmp/record.log
fi
echo "</M750>"
