#!/bin/bash
# pepper, jotabe, (c) Grupo SIESTA, 29-11-2007
#
# Guarda la configuración de los canales que se visualizan en la parrilla

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
PARRILLA_CHANNELS=${SERVER_ROOT}/cfg/parrilla_channels.txt

# Procesar parametros get/post
eval "`proccgi $*`"

# Recorrer campos de respuesta
CH_TMP=":"
for F_chID in ${!FORM_*}; do
	# Obtener identificador de canal
	TMP='$'${F_chID}
	eval "ValorParametro=$TMP"
	# Agregar a lista de canales
	CH_TMP="${CH_TMP}${ValorParametro}:"
done

# Guardar datos en fichero de configuracion
echo "${CH_TMP}" > $PARRILLA_CHANNELS

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/sincro/parrilla\"
	</script>
</head>
</html>"
