#!/bin/bash
# pepper, (c) Grupo SIESTA, 02-07-2007
#
# Guarda la configuración de los canales que se visualizan en la parrilla

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
PARRILLA_CHANNELS=${Cache}/parrilla_channels.txt

# Generar fichero con campos de respuesta
echo ${QUERY_STRING} | sed 's/&/\n/g' > ${PARRILLA_CHANNELS}.temp

# Recorrer campos de respuesta
CH_TMP=":"
while read line; do
	if [ ${#line} -ne 0 ]; then
		# Obtener identificador de canal
		chID=`echo "${line}" | cut -d"=" -f1`
		# Agregar a lista de canales
		CH_TMP="${CH_TMP}${chID}:"
	fi
done < ${PARRILLA_CHANNELS}.temp

# Eliminar ficheros temporales
rm -f ${PARRILLA_CHANNELS}.temp

# Guardar datos en fichero de configuracion
echo "${CH_TMP}" > $PARRILLA_CHANNELS

# Enviar redireccion html
http_header
echo "<html>
<head>
	<script type=\"text/javascript\">
		document.location.href=\"/cgi-bin/sincro/parrilla\"
	</script>
</head>
</html>"
