<table width="100%" border="0" cellspacing="0" cellpadding="2" align="center" class="borderTabla2">
<tr>
    <td class="fila titTabla"  bgcolor="#ffb310" align="center">Controles de MPlayer</td>
</tr>
<tr clas="txtNormal">
    <td class="fila" align="left">
        <h2>INTERACTIVE CONTROL</h2>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void" cols="2" cellspacing="0" cellpadding="0" class="txtNormal">
        <tr valign="top" align="left">
        <td class="txtNormal" width="10%"></td>
        <td class="txtNormal" width="89%">
        <p>MPlayer has a fully configurable, command-driven control
        layer which allows you to control MPlayer using keyboard,
        mouse, joystick or remote control (with LIRC). See the
        &minus;input option for ways to customize it.</p>
        </td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="10%"></td>
        <td class="txtNormal" width="89%">
        <p><b>keyboard control</b></p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>&lt;&minus; and &minus;&gt;</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 10 seconds.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>up and down</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 1 minute.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>pgup and pgdown</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 10 minutes.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>[ and ]</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase current playback speed by 10%.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>{ and }</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Halve/double current playback speed.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>backspace</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Reset playback speed to normal.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>&lt; and &gt;</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Go backward/forward in the playlist.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>ENTER</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Go forward in the playlist, even over the end.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>HOME and END</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>next/previous playtree entry in the parent list</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>INS and DEL (ASX playlist only)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>next/previous alternative source.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>p / SPACE</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Pause (pressing again unpauses).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Step forward. Pressing once will pause movie, every
        consecutive press will play one frame and then go into pause
        mode again (any other key unpauses).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>q / ESC</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Stop playing and quit.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>+ and -</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust audio delay by +/- 0.1 seconds.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>/ and *</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase volume.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>9 and 0</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase volume.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>m</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Mute sound.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p># (MPEG and Matroska only)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Cycle through the available audio tracks.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>f</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle fullscreen (also see &minus;fs).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>T</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle stay-on-top (also see &minus;ontop).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>w and e</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase pan-and-scan range.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>o</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle OSD states: none / seek / seek + timer / seek +
        timer + total time.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>d</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle frame dropping states: none / skip display / skip
        decoding (see &minus;framedrop and
        &minus;hardframedrop).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>v</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle subtitle visibility.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>b / j</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Cycle through the available subtitles.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>y and g</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Step forward/backward in the subtitle list.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>F</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle displaying &quot;forced subtitles&quot;.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>a</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle subtitle alignment: top / middle /
        bottom.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>x and z</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust subtitle delay by +/- 0.1 seconds.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>r and t</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Move subtitles up/down.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>i (&minus;edlout mode only)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Set EDL mark.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>s (&minus;vf screenshot only)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Take a screenshot.</p></td>
        </table>
        <!-- TABS -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="5" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="21%"></td>
        <td class="txtNormal" width="1%">
        
        <p>I</p>
        </td>
        <td class="txtNormal" width="10%"></td>
        <td class="txtNormal" width="36%">
        
        <p>Show filename on the OSD.</p>
        </td>
        <td class="txtNormal" width="29%">
        </td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>(The following keys are valid only when using a hardware
        accelerated video output (xv, (x)vidix, (x)mga, etc), the
        software equalizer (&minus;vf eq or &minus;vf eq2) or hue
        filter (&minus;vf hue).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>1 and 2</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust contrast.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>3 and 4</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust brightness.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>5 and 6</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust hue.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>7 and 8</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Adjust saturation.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>(The following keys are valid only when using the quartz
        or macosx video output driver.)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>command + 0</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Resize movie window to half its original size.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>command + 1</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Resize movie window to its original size.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>command + 2</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Resize movie window to double its original size.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>command + f</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle fullscreen (also see &minus;fs).</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>command + [ and command + ]</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Set movie window alpha.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>(The following keys are valid if you have a keyboard with
        multimedia keys.)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>PAUSE</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Pause.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>STOP</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Stop playing and quit.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>PREVIOUS and NEXT</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 1 minute.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>(The following keys are only valid if GUI support is
        compiled in and will take precedence over the keys defined
        above.)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>ENTER</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Start playing.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>ESC</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Stop playing.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>l</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Load file.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>t</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Load subtitle.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>c</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Open skin browser.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>p</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Open playlist.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>r</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Open preferences.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>(The following keys are only valid if you compiled with
        TV input support and will take precedence over the keys
        defined above.)</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>h and k</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Select previous/next channel.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>n</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Change norm.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>u</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Change channel list.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="10%"></td>
        <td class="txtNormal" width="89%">
        <p><b>mouse control</b></p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>button 3 and button 4</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 1 minute.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>button 5 and button 6</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase volume.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="10%"></td>
        <td class="txtNormal" width="89%">
        <p><b>joystick control</b></p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>left and right</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 10 seconds.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>up and down</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Seek backward/forward 1 minute.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>button 1</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>pause</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>button 2</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Toggle OSD states: none / seek / seek + timer / seek +
        timer + total time.</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="20%"></td>
        <td class="txtNormal" width="79%">
        <p>button 3 and button 4</p></td>
        </table>
        <!-- INDENTATION -->
        <table width="100%" border=0 rules="none" frame="void"
               cols="2" cellspacing="0" cellpadding="0">
        <tr valign="top" align="left">
        <td class="txtNormal" width="29%"></td>
        <td class="txtNormal" width="70%">
        <p>Decrease/increase volume.</p></td>
        </table>
    </td>
</tr>
</table>
