<table width="100%" border="0" cellspacing="0" cellpadding="2" align="center" class="borderTabla_sup borderTabla_inf">
	<tr><td class="filaTitulo" align="center">Controles de MPlayer</td></tr>

	<tr><td class="txtMP0">MPlayer tiene una capa de control totalmente configurable,
dirigida por órdenes, que le permite controlar MPlayer usando el teclado, el ratón,
un mando de juegos o un mando a distancia (usando LIRC). Vea la opción -input para
conocer las maneras de configurarlo.</td></tr>

	<tr><td class="txtMP1">CONTROL POR TECLADO</td></tr>

	<tr><td class="txtMP2">&lt;- y -&gt;</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 10 segundos.</td></tr>

	<tr><td class="txtMP2">arriba y abajo</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 1 minuto.</td></tr>

	<tr><td class="txtMP2">repág y avpág</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 10 minutos.</td></tr>

	<tr><td class="txtMP2">[ y ]</td></tr>
	<tr><td class="txtMP3">Aumenta/disminuye la velocidad de reproducción en un 10%.</td></tr>

	<tr><td class="txtMP2">{ y }</td></tr>
	<tr><td class="txtMP3">Dobla/Divide la velocidad de reproducción.</td></tr>

	<tr><td class="txtMP2">Retroceso</td></tr>
	<tr><td class="txtMP3">Devuelve la reproducción a la velocidad normal.</td></tr>

	<tr><td class="txtMP2">&lt; y &gt;</td></tr>
	<tr><td class="txtMP3">Retrocede/avanza en la lista de reproducción.</td></tr>

	<tr><td class="txtMP2">INICIO y FIN</td></tr>
	<tr><td class="txtMP3">Siguiente/anterior entrada del árbol de reproducción en la lista actual.</td></tr>

	<tr><td class="txtMP2">INS y SUPR</td></tr>
	<tr><td class="txtMP3">Siguiente/anterior fuente alternativa (solo para listas de reproducción ASX).</td></tr>

	<tr><td class="txtMP2">p / ESPACIO</td></tr>
	<tr><td class="txtMP3">Pausa la reproducción (cualquier tecla para salir del modo pausa).</td></tr>

	<tr><td class="txtMP2">.</td></tr>
	<tr><td class="txtMP3">Paso a paso. Presionando una vez detiene la reproducción,
cada pulsación posterior reproduce un frame y detiene la reproducción otra vez
(cualquier otra tecla hace retornar al modo normal).</td></tr>

	<tr><td class="txtMP2">q / ESC</td></tr>
	<tr><td class="txtMP3">Detiene la reproducción y termina.</td></tr>

	<tr><td class="txtMP2">+ y -</td></tr>
	<tr><td class="txtMP3">Ajusta el retardo de audio por +/- 0.1 segundos.</td></tr>

	<tr><td class="txtMP2">/ y *</td></tr>
	<tr><td class="txtMP3">Decrementa/incrementa el volumen.</td></tr>

	<tr><td class="txtMP2">9 y 0</td></tr>
	<tr><td class="txtMP3">Decrementa/incrementa el volumen.</td></tr>

	<tr><td class="txtMP2">m</td></tr>
	<tr><td class="txtMP3">Silencia el sonido.</td></tr>

	<tr><td class="txtMP2">_ (sólo MPEG-TS and libavformat)</td></tr>
	<tr><td class="txtMP3">Alterna entre las pistas de vídeo disponibles.</td></tr>

	<tr><td class="txtMP2"># (sólo MPEG, Matroska, AVI y libavformat)</td></tr>
	<tr><td class="txtMP3">Alterna entre las pistas de audio disponibles.</td></tr>

	<tr><td class="txtMP2">f</td></tr>
	<tr><td class="txtMP3">Cambia al modo de pantalla completa (vea también -fs).</td></tr>

	<tr><td class="txtMP2">T</td></tr>
	<tr><td class="txtMP3">Cambia al modo siempre-visible (vea también -ontop).</td></tr>

	<tr><td class="txtMP2">w y e</td></tr>
	<tr><td class="txtMP3">Decrementa/incrementa el rango de pan y scan.</td></tr>

	<tr><td class="txtMP2">o</td></tr>
	<tr><td class="txtMP3">Cambia entre los estados de OSD: nada / posición / posición + tiempo posición + tiempo + tiempo total.</td></tr>

	<tr><td class="txtMP2">d</td></tr>
	<tr><td class="txtMP3">Cambia el saltarse imágenes. Cambia entre los estados
del salto de imágenes: nada / saltar el mostrar en pantalla / saltar decodificación
(vea -framedrop y -hardframedrop).</td></tr>

	<tr><td class="txtMP2">v</td></tr>
	<tr><td class="txtMP3">Cambia la visibilidad de los subtítulos.</td></tr>

	<tr><td class="txtMP2">b y j</td></tr>
	<tr><td class="txtMP3">Alterna entre los subtítulos disponibles.</td></tr>

	<tr><td class="txtMP2">y y g</td></tr>
	<tr><td class="txtMP3">Paso adelante/atrás en la lista de subtítulos.</td></tr>

	<tr><td class="txtMP2">F</td></tr>
	<tr><td class="txtMP3">Cambia la visibilidad de "subtítulos forzados".</td></tr>

	<tr><td class="txtMP2">a</td></tr>
	<tr><td class="txtMP3">Cambia la alineación de los subtítulos: arriba/enmedio/abajo.</td></tr>

	<tr><td class="txtMP2">x y z</td></tr>
	<tr><td class="txtMP3">Ajusta el retardo de subtítulos por +/- 0.1 segundos.</td></tr>

	<tr><td class="txtMP2">r y t</td></tr>
	<tr><td class="txtMP3">Mueve los subtítulos arriba/abajo.</td></tr>

	<tr><td class="txtMP2">i (sólo modo -edlout)</td></tr>
	<tr><td class="txtMP3">Establece una marca EDL.</td></tr>

	<tr><td class="txtMP2">s (sólo -vf screenshot)</td></tr>
	<tr><td class="txtMP3">Realiza una captura de pantalla.</td></tr>

	<tr><td class="txtMP2">S (sólo -vf screenshot)</td></tr>
	<tr><td class="txtMP3">Comienza/para la toma de capturas de pantalla.</td></tr>

	<tr><td class="txtMP2">I</td></tr>
	<tr><td class="txtMP3">Muestra el nombre del fichero que se está reproduciendo en pantalla.</td></tr>

	<tr><td class="txtMP2">D (sólo -vo xvmc, -vf yadif, -vf kerndeint)</td></tr>
	<tr><td class="txtMP3">Activa/desactiva el desentrelazador.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando
se usa una salida de video acelerada por hardware (xv, (x)vidix, (x)mga, etc), el
ecualizador por software (-vf eq o -vf eq2) o el filtro de tonalidad (-vf hue)]</td></tr>

	<tr><td class="txtMP2">1 y 2</td></tr>
	<tr><td class="txtMP3">Ajusta el contraste.</td></tr>

	<tr><td class="txtMP2">3 y 4</td></tr>
	<tr><td class="txtMP3">Ajusta el brillo.</td></tr>

	<tr><td class="txtMP2">5 y 6</td></tr>
	<tr><td class="txtMP3">Ajusta el matiz.</td></tr>

	<tr><td class="txtMP2">7 y 8</td></tr>
	<tr><td class="txtMP3">Ajusta la saturación.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se usa quartz o el controlador de vídeo de macosx]</td></tr>

	<tr><td class="txtMP2">command + 0</td></tr>
	<tr><td class="txtMP3">Cambia el tamaño de la ventana a la mitad de su tamaño.</td></tr>

	<tr><td class="txtMP2">command + 1</td></tr>
	<tr><td class="txtMP3">Cambia el tamaño de la ventana a su tamaño original.</td></tr>

	<tr><td class="txtMP2">command + 2</td></tr>
	<tr><td class="txtMP3">Cambia el tamaño de la ventana al doble su tamaño original.</td></tr>

	<tr><td class="txtMP2">command + f</td></tr>
	<tr><td class="txtMP3">Cambia al modo de pantalla completa (vea también -fs).</td></tr>

	<tr><td class="txtMP2">command + [ y command + ]</td></tr>
	<tr><td class="txtMP3">Establece el canal alfa de la ventana de la película.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se usa el controlador de vídeo sdl]</td></tr>

	<tr><td class="txtMP2">c</td></tr>
	<tr><td class="txtMP3">Alterna entre los diferentes modos de pantalla completa.</td></tr>

	<tr><td class="txtMP2">n</td></tr>
	<tr><td class="txtMP3">Vuelve al modo original.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se usa un teclado multimedia]</td></tr>

	<tr><td class="txtMP2">PAUSE</td></tr>
	<tr><td class="txtMP3">Pausa la reproducción..</td></tr>

	<tr><td class="txtMP2">STOP</td></tr>
	<tr><td class="txtMP3">Detiene la reproducción y termina.</td></tr>

	<tr><td class="txtMP2">PREVIOUS y NEXT</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 1 minuto.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se ha
compilado con soporte para la interfaz gráfica y tienen prioridad sobre las anteriores]</td></tr>

	<tr><td class="txtMP2">ENTER</td></tr>
	<tr><td class="txtMP3">Comienza la reproducción.</td></tr>

	<tr><td class="txtMP2">ESC</td></tr>
	<tr><td class="txtMP3">Detiene la reproducción.</td></tr>

	<tr><td class="txtMP2">l</td></tr>
	<tr><td class="txtMP3">Carga un fichero.</td></tr>

	<tr><td class="txtMP2">t</td></tr>
	<tr><td class="txtMP3">Carga los subtítulos.</td></tr>

	<tr><td class="txtMP2">c</td></tr>
	<tr><td class="txtMP3">Abre el navegador de temas.</td></tr>

	<tr><td class="txtMP2">r</td></tr>
	<tr><td class="txtMP3">Abre el diálogo de preferencias.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se ha
compilado con soporte para la TV o DVB y tienen prioridad sobre las anteriores]</td></tr>

	<tr><td class="txtMP2">h y k</td></tr>
	<tr><td class="txtMP3">Selecciona el canal anterior/siguiente.</td></tr>

	<tr><td class="txtMP2">n</td></tr>
	<tr><td class="txtMP3">Cambia la norma.</td></tr>

	<tr><td class="txtMP2">u</td></tr>
	<tr><td class="txtMP3">Cambia la lista de canales.</td></tr>

	<tr><td class="txtMP4">[Las siguientes teclas son válidas únicamente cuando se ha
compilado con soporte para dvdnav: se usan para navegar por los menús]</td></tr>

	<tr><td class="txtMP2">Teclado numérico 8</td></tr>
	<tr><td class="txtMP3">Selecciona el botón hacia arriba.</td></tr>

	<tr><td class="txtMP2">Teclado numérico 2</td></tr>
	<tr><td class="txtMP3">Selecciona el botón hacia abajo.</td></tr>

	<tr><td class="txtMP2">Teclado numérico 4</td></tr>
	<tr><td class="txtMP3">Selecciona el botón hacia la izquierda.</td></tr>

	<tr><td class="txtMP2">Teclado numérico 6</td></tr>
	<tr><td class="txtMP3">Selecciona el botón hacia la derecha.</td></tr>

	<tr><td class="txtMP2">Teclado numérico 5</td></tr>
	<tr><td class="txtMP3">Vuelve al menú principal.</td></tr>

	<tr><td class="txtMP2">Teclado numérico 7</td></tr>
	<tr><td class="txtMP3">Vuelve al menú más cercano (el orden preferido es: capítulo-&gt;título-&gt;raíz).</td></tr>

	<tr><td class="txtMP2">Teclado numérico INTRO</td></tr>
	<tr><td class="txtMP3">Confirma la elección.</td></tr>

	<tr><td class="txtMP1">CONTROL POR RATÓN</td></tr>

	<tr><td class="txtMP2">Botón 3 y Botón 4</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 1 minuto.</td></tr>

	<tr><td class="txtMP2">Botón 4 y Botón 5</td></tr>
	<tr><td class="txtMP3">Aumenta/disminuye el volumen.</td></tr>

	<tr><td class="txtMP1">CONTROL POR JOYSTICK</td></tr>

	<tr><td class="txtMP2">izquierda y derecha</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 10 segundos.</td></tr>

	<tr><td class="txtMP2">arriba y abajo</td></tr>
	<tr><td class="txtMP3">Posiciona atrás/adelante 1 minuto.</td></tr>

	<tr><td class="txtMP2">botón 1</td></tr>
	<tr><td class="txtMP3">Pausa.</td></tr>

	<tr><td class="txtMP2">botón 2</td></tr>
	<tr><td class="txtMP3">Cambia los estados OSD: ninguno / búsqueda / búsqueda + contador / búsqueda + contador+ tiempo total.</td></tr>

	<tr><td class="txtMP2">botón 3</td></tr>
	<tr><td class="txtMP3">Aumenta/disminuye el volumen.</td></tr>
</table>
