#!/bin/bash
source ../www-setup
rm -f $Cache/*.ref $Cache/*.html $Cache/*.refXML
cat <<EOF
Content-type: text/html


<html>
<head>
`header.sh MartinO 300`

<title>Cache cleared</title>
</head>
<body>
<h2>Clear Cache</h2>

Cleared CRID cache!

</html> 

EOF
