#!/bin/bash
# pepper, (c) Grupo SIESTA, 03-12-2007
#
# Script que genera un fichero de comandos con las instrucciones necesarias para
# descargar a la máquina local una grabación completa, utilizando wget.

# Configurar entorno
source ../www-setup.shi

# Procesar parametros get/post
eval "`proccgi $*`"

# Obtener parametros
host=$FORM_host
port=$FORM_port
Cridfile=$FORM_cridfile
user=$FORM_user
pwd=$FORM_pwd
dir=$FORM_dir
offPC=$FORM_offpc
offGiga=$FORM_offgiga

# Por si el host viene con puerto, lo quitamos para el ftp y lo dejamos para el http
ftphost=`echo $host | cut -d":" -f1`

# Procesar fichero crid
eval `www-tools crid2var ${Cridfile}`

# Obtener carpeta de almacenamiento
recordingDir=`dirname $Cridfile`

# Log del proceso
echo "`date` Peticion descarga grabacion:
	$ftphost, $port, $Cridfile, ${fmpg0}*, $user, $pwd, Titulo: $Titulo" >> /tmp/download.log

# Descargar fichero de descarga
echo "Content-type: application/octet-stream"
echo "Content-Disposition: attachment; filename=descargar_grabacion.cmd"
echo ""
echo "wget --passive-ftp -P "$dir" ftp://${user}:${pwd}@${ftphost}:${port}${Cridfile}"
echo "wget --passive-ftp -P "$dir" ftp://${user}:${pwd}@${ftphost}:${port}${recordingDir}/${fmpg0}*"
if [ $offGiga = "SI" ]; then
    echo "wget http://${host}/cgi-bin/run/irsim?POWER"
fi
if [ $offPC = "SI" ]; then
    echo "shutdown -s"
fi
