#!/bin/bash
# pepper, jotabe, (c) Grupo SIESTA, 05-03-2008
#
# Mostrar informacion sobre grabacion pendiente.
# detalle-timer?pid&crid&utc

# Obtener parametros
pid=`echo $QUERY_STRING | cut -d"&" -f1`
Cridfile=`echo $QUERY_STRING | cut -d"&" -f2`

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
RECS_FILE=/data/RA_FILE

# Obtener identificador grabacion, guardas y sintonizador
id_rec=`grep $pid $RECS_FILE | awk '{print $1}'`
gIni=`grep $pid $RECS_FILE | awk '{print $8/60}'`
gFin=`grep $pid $RECS_FILE | awk '{print $9/60}'`
sint=`grep $pid $RECS_FILE | awk '{print $18+1}'`

# Enviar documento xml
xml_doc "/xsl/timerdetail.xsl"

# Resultado xml
echo "<M750>
	<TIMER_DETAIL>"

# Procesar resultado
if [ ${#id_rec} -ne 0 ]; then
	# Devolver datos timer
	echo "		<NUM_REC>$id_rec</NUM_REC>
		<GUARDA_INI>$gIni</GUARDA_INI>
		<GUARDA_FIN>$gFin</GUARDA_FIN>
		<SINT>$sint</SINT>"

	# Procesar fichero crid
	./crid2xml.sh $Cridfile
else
	# Error identificador no encontrado
	echo "		<ERROR>La grabación pendiente con identificador $pid no se encuentra.</ERROR>"
fi

# Final xml
echo "	</TIMER_DETAIL>
</M750>"
