#!/bin/bash 
# Martin Ostermann, 2005-08-21
# Modified by pepper to return XML, 25/04/2007

source ../www-setup.shi
source fweb.shi

if [ $# = 1 ]; then
	Cridfile=$1
else
	Cridfile=$QUERY_STRING
fi
Basename=`basename $Cridfile .crid`

declare -a Crid0
declare -a Crid1
declare -a Crid2
declare -a Crid3

Crid0=( `hexdump -n 50 -e '11/4 "%d \n" 1/2 "%d \n" 1/4 "%d \n" ' $Cridfile ` )
c1=${Crid0[12]}
s1=$(( 50 + $c1 ))
n1=8
RecordingState=${Crid0[3]}
Begin=${Crid0[4]}
End=${Crid0[5]}
RecordingFlag=${Crid0[9]}

if [ "$QUERY_STRING" = "save" ] ; then
	splitInputData "`cat`"
	echo "crided -T $Title -S $EPGshort -L $EPGlong $PATH_INFO" >> /tmp/kk.tmp
	crided -T "$Title" -S "$EPGshort" -L "$EPGlong" "$PATH_INFO"	
else	
	#Title=`dd bs=1 skip=$(($s1-$c1)) count=$c1 2>/dev/null <$Cridfile`
	Title=`hexdump -v -s $(($s1-$c1)) -n $c1 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/^&#5;//'`
	
	Crid1=( `hexdump -s $s1 -n $n1 -e "2/4 \"%d \n\" " $Cridfile ` )
	c2=${Crid1[1]}
	s2=$(( $s1+$n1+$c2 ))
	
	c3=$c2
	s3=$s2
	
	f=${Crid1[0]}
	while [ $f != 0 ] ; do
		n2=24
		Crid2=( `hexdump -s $s2 -n $n2 -e "6/4 \"%d \n\" " $Cridfile `)
		c3=${Crid2[5]}
		s3=$(( $s2+$n2+$c3 ))
		s2=$s3
		c2=$c3
		f=$(($f-1))
	done
	
	if true ; then
		n3=4
		Crid3=( `hexdump -s $s3 -n $n3 -e "1/4 \"%d \n\" " $Cridfile `)
		c4=${Crid3[0]}
		s4=$(( $s3+$n3+$c4 ))
		n4=4
	
		#echo c1=$c1  c2=$c2  c3=$c3  c4=$c4
		#Crid4=( `hexdump -s $s4 -n $n4 -e "1/4 \"%d \n\" " $Cridfile` )
	
		if [ $c3 != 0 ]; then
			#EPGshort=`dd bs=1 skip=$(($s3-$c3)) count=$c3 2>/dev/null <$Cridfile`
			EPGshort=`hexdump -v -s $(($s3-$c3)) -n $c3 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/^&#5;//'`
		fi
		if [ $c4 != 0 ]; then
			#EPGlong=`dd bs=1 skip=$(($s4-$c4)) count=$c4 2>/dev/null <$Cridfile`
			EPGlong=`hexdump -v -s $(($s4-$c4)) -n $c4 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//' -e 's/&#138;/\&#10;/g'`
		fi
	fi
fi	

SenderInfo=`grep ${Basename: -5}$ /var/etc/services.txt`
SenderName=`echo ${SenderInfo:0:20} | iso2html | sed -e 's/^&#5;//'`
DiaSemana=([1]="Lun" [2]="Mar" [3]="Mie" [4]="Jue" [5]="Vie" [6]="Sab" [7]="Dom")
ds=`awk "BEGIN {print strftime( \"%u\" , $Begin) }"`
dateFormatIni=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $Begin) }"`
dateFormatIni="$dateFormatIni, ${DiaSemana[ds]}"
ds=`awk "BEGIN {print strftime( \"%u\" , $End) }"`
dateFormatFin=`awk "BEGIN {print strftime( \"%d.%m.%y %H:%M\" , $End) }"`
dateFormatFin="$dateFormatFin, ${DiaSemana[ds]}"

# Enviar documento html
html_doc_start "M750T - Edición datos de Grabación" "" "-a----bm"

# Respuesta html
html_top "Edición datos de Grabación" "" "" ""

cat <<-EOF
    <script>
       cridfile="$Cridfile";
       function guardar() {
           document.forms[0].action="/cgi-bin/crid/save-title"+cridfile+"?save";
           document.forms[0].method="post";
           document.forms[0].submit();
       }
    </script>
    <br><br>
    <table width="98%" border="0" cellspacing="0" cellpadding="1" align="center">
    <tr>
      <td class="titChannel">
        $SenderName<br/>
        $dateFormatIni - $dateFormatFin
      </td>
    </tr>
    <tr>
      <td class="titChannel" height="4"></td>
    </tr>
    <tr>
      <td class="txtNormal" align="left" valign="top">
            <input type="text" name="Title" size="50" class="cajaPlana" value="$Title"><br/><br/>
            <input type="text" name="EPGshort" size="75" class="cajaPlana" value="$EPGshort"><br/><br/>
        <p><textarea cols="120" class="cajaPlana" rows="20" name="EPGlong" MAXLENGTH="800">$EPGlong</textarea></p>
        <input class="txtNormal" type="button" value="Guardar" onclick="guardar()" />&nbsp;
        <input class="txtNormal" type="reset" value="Deshacer Cambios" /><br/>
      </td>
    </tr>
    </table>
    </p>
EOF
# Final html
html_doc_end
