#!/bin/bash
# pepper, (c) grupo SIESTA, 04-12-2007
#
# Script que devuelve el tamaño en bytes de un fichero

# Obtener parametros
if [ $# != 0 ]; then
	file=`echo $1 | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/%2F/\//g'`
else
    file=`echo $QUERY_STRING | sed -e 's/%20/ /g' | sed -e 's/%3A/\:/g' | sed -e 's/%5C/\//g' | sed -e 's/%2F/\//g'`
fi

# Devolver resultado
echo ""
if [ "Z$file" != "Z"  ]; then
	if [ -f $file ]; then
	    #totalBytes=(`wc -c $file`)
	    declare -a totalBytes
	    totalBytes=(`ls -l $file`)
	    echo ${totalBytes[4]}
	else
	    echo "0"
	fi
else
    echo "0"
fi
