#!/bin/sh
source ../www-setup
. theme header "Nueva Programación" = MartinO 300

cat << ---EOT---
<h2>Datos de la nueva programacion:</h2> <p>
<FORM ACTION="${DIR_NAME}/newtimer.post?analyze" METHOD="post">
<table>
<tr>
  <td>Canal, Fecha, Inicio-Fin:</td>
  <td><input type="text" name="program" value="" size="45"></td>
</tr><tr>
  <td>Titulo:</td>
  <td><input type="text" name="title" value="" size="45"></td>
</tr><tr>
  <td>Subtitulo:</td>
  <td><input type="text" name="shortdesc" value="" size="45"></td>
</tr><tr>
<td colspan=2><TEXTAREA wrap="virtual" name="longdesc" rows=15 cols=80 MAXLENGTH=1600></TEXTAREA></td>
</tr><tr>
<td colspan=2>
<INPUT type="Submit" VALUE="Analizar">
<INPUT type="Reset" VALUE="Borrar">
</td>
</tr></table>
</FORM>
Bitte beachten Sie diese<a href="/cgi-bin/display/static/crid/info-timer-modification.body?Title=Bearbeitung%20von%20Timern&Heading=Probleme%20beim%20Bearbeiten%20von%20Timern&Author=MartinO"> |Hinweise|</a>!
---EOT---

. theme footer

