#!/bin/bash 
# Martin Ostermann, 2005-08-21
source ../www-setup
if [ $# = 1 ]; then
	Cridfile=$1
else
	Cridfile=$QUERY_STRING
fi
Basename=`basename $Cridfile .crid`
Cachefile=${Cache}/${Basename}.body

if [ $Cridfile -nt $Cachefile ] ; then
	
	declare -a Crid0
	declare -a Crid1
	declare -a Crid2
	declare -a Crid3
	
	Crid0=( `hexdump -n 50 -e '11/4 "%d \n" 1/2 "%d \n" 1/4 "%d \n" ' $Cridfile ` )
	c1=${Crid0[12]}
	s1=$(( 50 + $c1 ))
	n1=8
	
	#Title=`dd bs=1 skip=$(($s1-$c1)) count=$c1 2>/dev/null <$Cridfile | iso2html`
	Title=`hexdump -v -s $(($s1-$c1)) -n $c1 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br>/g' `
	Begin=${Crid0[4]}
	End=${Crid0[5]}
	
	Crid1=( `hexdump -s $s1 -n $n1 -e "2/4 \"%d \n\" " $Cridfile ` )
	c2=${Crid1[1]}
	s2=$(( $s1+$n1+$c2 ))
	
	c3=$c2
	s3=$s2
	
	f=${Crid1[0]}
	while [ $f != 0 ] ; do
		n2=24
		Crid2=( `hexdump -s $s2 -n $n2 -e "6/4 \"%d \n\" " $Cridfile `)
		c3=${Crid2[5]}
		s3=$(( $s2+$n2+$c3 ))
		s2=$s3
		c2=$c3
		f=$(($f-1))
	done
	
	if true ; then
		n3=4
		Crid3=( `hexdump -s $s3 -n $n3 -e "1/4 \"%d \n\" " $Cridfile `)
		c4=${Crid3[0]}
		s4=$(( $s3+$n3+$c4 ))
		n4=4
	
		#echo c1=$c1  c2=$c2  c3=$c3  c4=$c4
		#Crid4=( `hexdump -s $s4 -n $n4 -e "1/4 \"%d \n\" " $Cridfile` )
	
		if [ $c3 != 0 ]; then
			#EPGshort=`dd bs=1 skip=$(($s3-$c3)) count=$c3 2>/dev/null <$Cridfile | iso2html`
			EPGshort=`hexdump -v -s $(($s3-$c3)) -n $c3 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br>/g' `
		fi
		if [ $c4 != 0 ]; then
			#EPGlong=`dd bs=1 skip=$(($s4-$c4)) count=$c4 2>/dev/null <$Cridfile|iso2html`
			EPGlong=`hexdump -v -s $(($s4-$c4)) -n $c4 -e "/1 \"&#%d;\"" $Cridfile | sed -e 's/&#5;//g' -e 's/&#138;/<br>/g' `
		fi
	fi
	
	SenderInfo=`grep ${Basename: -5}$ /var/etc/services.txt`
	SenderName=`echo ${SenderInfo:0:20} |iso2html| sed -e 's/&#5;//g' -e 's/&#138;/<br>/g'`

	( cat <<-EOF
	<h2>$Title</h2>
	`awk "BEGIN {print \"${SenderName} -  \" strftime( \"%d.%m. %H:%M\" , $Begin) \"-\" strftime( \"%H:%M\" , $End) \" : \" ($End-$Begin)/60 \"min\" }"` <p>
	
	$EPGshort<p>
	
	$EPGlong<p>

	<a href="$DIR_NAME/edit-title${Cridfile}">|Editieren|</a>
	EOF
	) > $Cachefile

fi

. theme header "Aufnahme" "=" MartinO 300
cat $Cachefile
. theme footer
