#!/bin/bash
# (c) Grupo SIESTA, 03-11-2007
#
# Devolver lista de grabaciones archivadas

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
USB_DISK=/var/media/USB-HDD

# Obtener parametros
if [ "$QUERY_STRING" != "" ] ; then
	if [ "$QUERY_STRING" = "serie" ]; then
		rm -f ${Cache}/.time_sort
		touch ${Cache}/.serie_sort
		xsl=archivo_serie_sort.xsl
	else
		rm -f ${Cache}/.serie_sort
		touch ${Cache}/.time_sort
		xsl=archivo_time_sort.xsl
	fi
else
	if [ -f ${Cache}/.serie_sort ]; then
		xsl=archivo_serie_sort.xsl
	else
		xsl=archivo_time_sort.xsl
	fi
fi

# Comprobacion USB-HDD montado
info=""
USB_MOUNTED=`grep ${USB_DISK} /proc/mounts | wc -l`
if [ ${USB_MOUNTED} -eq 0 ]; then
	info="No se puede acceder a la carpeta de archivo de grabaciones porque no hay acceso al disco duro."
# Comprobar carpeta de archivo grabaciones
elif [ ! -d ${ARCHIVO_GRABACIONES} ]; then
	info="No existe la carpeta $ARCHIVO_GRABACIONES
	<br><br>
	Revise la configuración <a href=\"/cgi-bin/box/configSIESTA\">SIESTA</a> o cree esta carpeta para tener acceso a la función de archivo de grabaciones."
# Contar nº de grabaciones
else
	numCrids=`ls -la $ARCHIVO_GRABACIONES/*.crid 2>/dev/null | wc -l`
	if [ $numCrids -eq 0 ]; then
		info="No existe ninguna grabación archivada en la carpeta $ARCHIVO_GRABACIONES"
	fi
fi

# Mostrar error o procesar carpeta
if [ ${#info} -ne 0 ]; then
	# Enviar documento html
	html_doc_start "M750T - Archivo de Grabaciones" "" "------b-"
	html_top "Archivo de Grabaciones" "" "" ""
	echo "			<br>
			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\" align=\"center\">
				<tr>
					<td class=\"titChannel\" align=\"center\">
						<font class=\"txtAvisos\">$info</font>
					</td>
				</tr>
			</table>"
	html_doc_end no
else
	# Procesar carpeta de archivo grabaciones
	./lista-crid2xml.sh $ARCHIVO_GRABACIONES RECORDINGS $xsl
fi
