#!/bin/bash
# (c) Grupo SIESTA, 03-11-2007
#
# Devolver lista de grabaciones realizadas

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi
USB_DISK=/var/media/USB-HDD

# Obtener parametros
if [ "$QUERY_STRING" != "" ] ; then
  serieTime=`echo ${QUERY_STRING} | cut -d"&" -f1`
  isDir=`echo ${QUERY_STRING} | grep "\&" | wc -l`
  if [ $isDir -gt 0 ]; then
  	RecordingFolder=`echo ${QUERY_STRING} | cut -d"&" -f2`
  else
  	RecordingFolder=""
  fi
  if [ "$serieTime" = "serie" ]; then
    rm -f ${Cache}/.time_sort
    touch ${Cache}/.serie_sort
    if [ $RecordingFolder != "" ]; then
        xsl=record2_serie_sort.xsl
    else
        xsl=record_serie_sort.xsl
    fi
  elif [ "$serieTime" = "time" ]; then
    rm -f ${Cache}/.serie_sort
    touch ${Cache}/.time_sort
    if [ $RecordingFolder != "" ]; then
        xsl=record2_time_sort.xsl
    else
        xsl=record_time_sort.xsl
    fi
  fi
else
  if [ -f ${Cache}/.serie_sort ]; then
    xsl=record_serie_sort.xsl
  else
    xsl=record_time_sort.xsl
  fi
fi

# Obtenemos carpeta de grabaciones
if [ "$RecordingFolder" = "" ]; then
    RecordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`
fi

# Comprobacion USB-HDD montado
info=""
USB_MOUNTED=`grep ${USB_DISK} /proc/mounts | wc -l`
if [ ${USB_MOUNTED} -eq 0 ]; then
  info="No se puede acceder a la carpeta de grabaciones realizadas porque no hay acceso al disco duro."
# Comprobar carpeta de archivo grabaciones
elif [ ! -d ${RecordingFolder} ]; then
  info="No existe la carpeta $RecordingFolder
  <br><br>
  Revise la configuración de la carpeta de grabaciones de su gigaset."
# Contar nº de grabaciones
else
  numCrids=`ls -la $RecordingFolder/*.crid 2>/dev/null | wc -l`
  if [ $numCrids -eq 0 ]; then
    info="No existe ninguna grabación en la carpeta $RecordingFolder"
    ####Meter boton de vaciado de fragmentos
  fi
fi

# Mostrar error o procesar carpeta
if [ ${#info} -ne 0 ]; then
  # Enviar documento html
  html_doc_start "M750T - Grabaciones Realizadas" "" "------b-"
  html_top "Grabaciones Realizadas" "" "" ""
  echo "      <br>
      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\" align=\"center\">
        <tr>
          <td class=\"titChannel\" align=\"center\">
            <font class=\"txtAvisos\">$info</font>
          </td>
        </tr>
      </table>"
  html_doc_end no
else
  # Procesar carpeta de grabaciones
  ./lista-crid2xml.sh $RecordingFolder RECORDINGS $xsl
fi
