#!/bin/bash
# (c) Grupo SIESTA, 03-11-2007
#
# Devolver lista de grabaciones archivadas
# ver-lista-archivo?[serie|time]

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
USB_DISK=/var/media/USB-HDD

# Obtener parametros
case ${QUERY_STRING} in
	serie)
		rm -f ${SERVER_ROOT}/cfg/.time_sort
		touch ${SERVER_ROOT}/cfg/.serie_sort
		;;
	time)
		touch ${SERVER_ROOT}/cfg/.time_sort
		rm -f ${SERVER_ROOT}/cfg/.serie_sort
		;;
esac

# Obtener orden
[ -f ${SERVER_ROOT}/cfg/.serie_sort ] && orden=serie || orden=time

# Comprobacion USB-HDD montado
info=""
USB_MOUNTED=`grep ${USB_DISK} /proc/mounts | wc -l`
if [ ${USB_MOUNTED} -eq 0 ]; then
	info="No se puede acceder a la carpeta de archivo de grabaciones porque no hay acceso al disco duro."
# Comprobar carpeta de archivo grabaciones
elif [ ! -d ${ARCHIVO_GRABACIONES} ]; then
	info="No existe la carpeta $ARCHIVO_GRABACIONES
	<br><br>
	Revise la configuración <a href=\"/cgi-bin/box/configSIESTA\">SIESTA</a> o cree esta carpeta para tener acceso a la función de archivo de grabaciones."
# Contar nº de grabaciones
else
	numCrids=`ls -la $ARCHIVO_GRABACIONES/*.crid 2>/dev/null | wc -l`
	[ $numCrids -eq 0 ] && info="No existe ninguna grabación archivada en la carpeta $ARCHIVO_GRABACIONES"
fi

# Mostrar error o procesar carpeta
if [ ${#info} -ne 0 ]; then
	# Enviar documento html
	html_doc_start "M750T - Archivo de Grabaciones" "" "-----b-"
	html_top "Archivo de Grabaciones" "" "" ""
	print_aviso_info "${info}"
else
	# Proxima carpeta a usar para lista de grabaciones
	carpeta_ver=/var/media/PC1/Video
	[ -f ${SERVER_ROOT}/cfg/.carpeta_ver.txt ] && carpeta_ver=`cat ${SERVER_ROOT}/cfg/.carpeta_ver.txt`

	# Procesar carpeta de archivo grabaciones
	./lista-crid2xml.sh $ARCHIVO_GRABACIONES record $orden $carpeta_ver
fi
