#!/bin/bash 
# (c) Grupo SIESTA, 06-08-2007
#
# Devolver grabaciones realizadas

# Configurar entorno
source ../www-setup.shi
source ../fweb.shi

# Obtener parametros
if [ "$QUERY_STRING" != "" ] ; then
	if [ "$QUERY_STRING" = "serie" ]; then
		rm -f ${Cache}/.time_sort
		touch ${Cache}/.serie_sort
		xsl=record_serie_sort.xsl
	else
		rm -f ${Cache}/.serie_sort
		touch ${Cache}/.time_sort
		xsl=record_time_sort.xsl
	fi
else
	if [ -f ${Cache}/.serie_sort ]; then
		xsl=record_serie_sort.xsl
	else
		xsl=record_time_sort.xsl
	fi
fi

# Obtenemos carpeta de grabaciones
RecordingFolder=`sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt`
# RecordingFolder=/var/cache

# Comprobar carpeta
if [ -d $RecordingFolder ]; then
	# Procesar carpeta de grabaciones
	./lista-crid2xml $RecordingFolder RECORDINGS $xsl
else
	# Enviar documento html
	html_doc_start "M750T - Grabaciones Realizadas" "" "------b-"

	# Respuesta html
	html_top "Grabaciones Realizadas" "" ""
	echo "			<br>
			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\" align=\"center\">
				<tr>
					<td class=\"titChannel\" align=\"center\">
						<font class=\"txtAvisos\">
						No se pueden mostrar las grabaciones realizadas porque no hay acceso al disco duro.
						</font>
					</td>
				</tr>
			</table>"

	# Final html
	html_doc_end no
fi
