#!/bin/bash
source ../www-setup
if [ "$QUERY_STRING" != "" ] ; then
    if [ "$QUERY_STRING" = "serie" ]; then
        rm -f $Cache/.time_sort
        touch $Cache/.serie_sort
        xsl=record_serie_sort.xsl
    else
        rm -f $Cache/.serie_sort
        touch $Cache/.time_sort
        xsl=record_time_sort.xsl
    fi
else
    if [ -f $Cache/.serie_sort ]; then
        xsl=record_serie_sort.xsl
    else
        xsl=record_time_sort.xsl
    fi
fi

./recordingsXML `sed -n -e "/DeviceRecordingFolder/ s/D.* *\(.pvr.*\)/\1/p" /var/etc/settings.txt` RECORDINGS $xsl
