#!/bin/bash
# pepper, jotabe, (c) Grupo SIESTA, 06-03-2008
#
# Visualizar contenido fichero RA_FILE

# Configurar entorno
source ../www-setup.shi
source fweb.shi
validate_login
source ../box/fshow.shi
FICHERO=/data/RA_FILE

# Ajustar variables para script show
SCRIPT_NAME=/cgi-bin/box/show
PATH_INFO=${FICHERO}
action="view"
flags="-ev-"

# Enviar documento html
print_top ${FICHERO} ${flags} ""
echo "			<tr>"
echo "				<td class=\"fila\">"
print_actions
echo "					<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFEEE6\">
						<tr class=\"titChannel\">
							<td width=\"20%\">Fecha/Hora Inicio</td>
							<td width=\"20%\">Fecha/Hora Fin</td>
							<td width=\"20%\" align=\"center\">Guarda Inicial (min)</td>
							<td width=\"20%\" align=\"center\">Guarda Final (min)</td>
							<td width=\"10%\" align=\"center\">Prioridad</td>
							<td width=\"10%\" align=\"center\">ID Grab</td>
						</tr>"

# Recorrer fichero RA_FILE
[ -f ${FICHERO} ] && format_RAFile.awk ${FICHERO}

# Final html
echo "					</table>"
print_actions
echo "				</td>"
echo "			</tr>"
print_bottom
