#!/bin/bash 
# by pepper, 6/6/2007 (C) grupo SIESTA

echo Content-type: text/html
echo ""

cat <<- ---EOT---
<html>
<title>M750T - Explorador /data/SM_FILE</title>
<meta http-equiv="refresh" content="600" />
<link href="/sincro/img/m740.ico" rel="shortcut icon"></link>
<link href="/sincro/css/estilos.css" rel="stylesheet" type="text/css"></link>
<script language="JavaScript" src="/sincro/js/ajax.js"></script>
<script language="JavaScript" src="/sincro/js/navigator.js"></script>
<script language="JavaScript" src="/sincro/js/controlenviar.js"></script>
<script language="JavaScript" src="/sincro/js/fechasOp.js"></script>
<script language="JavaScript" src="/sincro/js/botones.js"></script>
<body bgcolor="#FFFFFF">
  <div align="center"><p><font class="titPag">M750T EPG</font></p></div>
  <div align="center"><font class="subTitPag">Explorador de archivos: /data/SM_FILE</font></div>
  <script language="JavaScript">barra_botones();</script>
  <table width="98%" border="0" cellspacing="0" cellpadding="2" align="center"  class="borderTabla2">
  <tr>
    <td class="fila titTabla"  bgcolor="#ffb310">
<a class="titChannel" href="/cgi-bin/box/show/">&nbsp;/</a> <font class="titChannel"><a href="/cgi-bin/box/show//data">data</a> / SM_FILE</font>
  </td></tr>
  <tr>
    <td class="fila">
<p>
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?hexdump">HEXDUMP</a>]
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?edit">EDIT</a>]
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?send">DOWNLOAD</a>]
<pre style="background-color:#FFEEE6; padding:.2em" >
---EOT---

cat /data/SM_FILE | sed -e 's/Series_ID/<hr width="100%" size="2"><font color="#0000FF" style="font-weight: bolder;">Series_ID<\/font>/g' | sed -e 's/EPG_title/<font color="#0000FF" style="font-weight: bolder;">EPG_title<\/font>/g'

cat <<- ---EOT---
</pre>
<p>
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?hexdump">HEXDUMP</a>]
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?edit">EDIT</a>]
[<a class="txtNormal" href="/cgi-bin/box/show/data/SM_FILE?send">DOWNLOAD</a>]
  </table>
  <table width="98%" border="0" cellspacing="0" cellpadding="2" align="center">
  <tr>
    <td class="txtNormal" align="right">Explorador basado en código de <a href="http://www.open7x0.org/wiki/Benutzer:Lemmi">Lemmi</a> bajo licencia <a href="http://www.gnu.de/gpl-ger.html">GPL</a></td>
  </tr>
  </table>
  <script language="JavaScript">barra_botones();</script>
</body>
</html>
---EOT---
